### ISSUE TITLE
Failed to add resource root org.apache.felix.configadmin-1.8.8.jar

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1002]
I am currently experiencing this when the tar.gz patch is deployed. It's also been failing consistently on the stability build for some time.

```
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to add resource root 'org.apache.felix.configadmin-1.8.8.jar' at path 'org.apache.felix.configadmin-1.8.8.jar' (position: END_TAG seen ...</filter>\n        </resource-root>... @36:25) caused by: java.io.FileNotFoundException: /mnt/hudson_workspace/workspace/wildfly-camel-stability/examples/itests/target/wildfly-9.0.2.Final/modules/system/layers/fuse/org/jboss/gravia/main/org.apache.felix.configadmin-1.8.8.jar (No such file or directory)
	at org.jboss.modules.ModuleXmlParser.parseResourceRoot(ModuleXmlParser.java:802) [jboss-modules.jar:1.4.3.Final]
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:646) [jboss-modules.jar:1.4.3.Final]
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:446) [jboss-modules.jar:1.4.3.Final]
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:261) [jboss-modules.jar:1.4.3.Final]
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:148) [jboss-modules.jar:1.4.3.Final]
	... 21 more
```

**Comment by jamesnetherton** [comment]
It's an order of processing issue, we need to be explicit about [what's excluded](https://github.com/wildfly-extras/wildfly-camel/blob/master/modules/etc/smartics/skipped-modules.xml#L113) until my upstream smartics fixes are merged.
