### ISSUE TITLE
ElasticSearch integration fails with path.home is not configured

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1006]
```
Caused by: java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:82)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
	at org.apache.camel.component.elasticsearch.ElasticsearchEndpoint.doStart(ElasticsearchEndpoint.java:103)
```

**Comment by tdiesler** [comment]
Done
