### ISSUE TITLE
CDI fails with multiple named route builders

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1028]
```
15:19:04,139 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."camel-cdi-tests.jar".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."camel-cdi-tests.jar".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type RouteBuilderD with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject org.wildfly.camel.test.cdi.CDIIntegrationTest.routesD
  at org.wildfly.camel.test.cdi.CDIIntegrationTest.routesD(CDIIntegrationTest.java:0)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Managed Bean [class org.wildfly.camel.test.cdi.subA.RouteBuilderD] with qualifiers [@ContextName @Any]
```

**Comment by tdiesler** [comment]
Done
