### ISSUE TITLE
Dozer classloading may fail with spring based context

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1035]
```
Caused by: org.dozer.MappingException: java.lang.ClassNotFoundException: generated.ABCOrder from [Module "net.sf.dozer:main" from local module loader @64b8f8f4 (finder: local module finder @2db0f6b2 (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/smoke/target/wildfly-9.0.2.Final/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/smoke/target/wildfly-9.0.2.Final/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/smoke/target/wildfly-9.0.2.Final/modules/system/layers/base))]
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82)
	at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:43)
	at org.dozer.util.MappingUtils.loadClass(MappingUtils.java:224)
	at org.dozer.loader.DozerBuilder$MappingBuilder.classA(DozerBuilder.java:129)
	at org.dozer.loader.xml.XMLParser.parseMapping(XMLParser.java:190)
	at org.dozer.loader.xml.XMLParser.read(XMLParser.java:137)
	at org.dozer.loader.xml.XMLParser.read(XMLParser.java:43)
	at org.dozer.loader.xml.MappingStreamReader.read(MappingStreamReader.java:51)
	at org.dozer.DozerBeanMapper.addMapping(DozerBeanMapper.java:247)
	at org.apache.camel.component.dozer.DozerEndpoint.createDozerBeanMapper(DozerEndpoint.java:130)
	at org.apache.camel.component.dozer.DozerEndpoint.doStart(DozerEndpoint.java:111)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3232)
	at org.apache.camel.impl.DefaultCamelContext.doAddService(DefaultCamelContext.java:1212)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1173)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1169)
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:586)
	... 47 more
Caused by: java.lang.ClassNotFoundException: generated.ABCOrder from [Module "net.sf.dozer:main" from local module loader @64b8f8f4 (finder: local module finder @2db0f6b2 (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/smoke/target/wildfly-9.0.2.Final/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/smoke/target/wildfly-9.0.2.Final/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/smoke/target/wildfly-9.0.2.Final/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:909)
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:943)
	at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:41)
	... 62 more
```

CrossRef: https://issues.jboss.org/browse/ENTESB-4618

**Comment by tdiesler** [comment]
Done
