### ISSUE TITLE
Dozer cannot find org.apache.el.ExpressionFactory

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1039]
```
javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:102)
	at javax.el.FactoryFinder.find(FactoryFinder.java:186)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:197)
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:168)
	at org.wildfly.camel.test.dozer.ELIntegrationTest.testStatelessSessionBean(ELIntegrationTest.java:48)
```

**Comment by tdiesler** [comment]
Only shows on EAP
