### ISSUE TITLE
Investigate camel-core swarm in VM startup failure

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1059]
```
Caused by: java.lang.NumberFormatException: For input string: "0:0:0:0:0:0:0:8080"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:216)
	at java.net.URL.<init>(URL.java:615)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at org.wildfly.extension.camel.service.CamelUndertowHostService.getConnectionURL(CamelUndertowHostService.java:126)
	at org.wildfly.extension.camel.service.CamelUndertowHostService.start(CamelUndertowHostService.java:91)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jamesnetherton** [comment]
It's probably because of this: https://github.com/wildfly-extras/wildfly-camel/issues/1038

**Comment by tdiesler** [comment]
Moved to https://github.com/wildfly-swarm/wildfly-swarm-camel/issues/11
