### ISSUE TITLE
Cannot resolve cxf://bean:cxfProducer due to CNFE

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1114]
```
org.wildfly.camel.test.camel.cxf.CXFWebServiceConsumerTest  Time elapsed: 1.962 sec  <<< ERROR!
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route producerRoute at: >>> To[cxf:bean:cxfProducer] <<< in route: Route(producerRoute)[[From[direct:start]] -> [To[cxf:bean:cx... because of Failed to resolve endpoint: cxf://bean:cxfProducer due to: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cxfProducer': Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: org/apache/cxf/frontend/ServerFactoryBean
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1060)
	at org.apache.camel.spring.spi.ApplicationContextRegistry.lookupByNameAndType(ApplicationContextRegistry.java:47)
	at org.apache.camel.impl.PropertyPlaceholderDelegateRegistry.lookupByNameAndType(PropertyPlaceholderDelegateRegistry.java:63)
	at org.apache.camel.util.CamelContextHelper.lookup(CamelContextHelper.java:137)
	at org.apache.camel.util.CamelContextHelper.mandatoryLookup(CamelContextHelper.java:157)
	at org.apache.camel.component.cxf.CxfComponent.createCxfSpringEndpoint(CxfComponent.java:120)
	at org.apache.camel.component.cxf.CxfComponent.createEndpoint(CxfComponent.java:89)
	at org.apache.camel.impl.DefaultComponent.createEndpoint(DefaultComponent.java:114)
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:568)
```

**Comment by tdiesler** [comment]
done
