### ISSUE TITLE
DuplicateServiceException thrown from Spring Camel Context startup

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1128]
A number of the Spring context tests throw warnings on startup like the following.

```
[0m[33m04:18:38,216 WARN  [org.apache.camel.util.EventHelper] (MSC service thread 1-3) Error notifying event Starting CamelContext: contextScan. This exception will be ignored. : org.jboss.msc.service.DuplicateServiceException: Service jboss.naming.context.java.jboss.camel.context.contextScan is already registered
	at org.jboss.msc.service.ServiceRegistrationImpl.setInstance(ServiceRegistrationImpl.java:158)
	at org.jboss.msc.service.ServiceControllerImpl.startInstallation(ServiceControllerImpl.java:235)
	at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:768)
	at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
	at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
	at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:317)
	at org.wildfly.extension.camel.ee.CamelContextBindingService.addService(CamelContextBindingService.java:65)
	at org.wildfly.extension.camel.ee.EESubsystemExtension.addCamelContext(EESubsystemExtension.java:65)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl$2.accept(CamelContextRegistryService.java:237)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl$2.accept(CamelContextRegistryService.java:234)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.wildfly.extension.camel.parser.CamelSubsystemAdd.processExtensions(CamelSubsystemAdd.java:128)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl.addCamelContext(CamelContextRegistryService.java:234)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl.access$000(CamelContextRegistryService.java:146)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl$1.notify(CamelContextRegistryService.java:211)
	at org.apache.camel.util.EventHelper.doNotifyEvent(EventHelper.java:805)
	at org.apache.camel.util.EventHelper.notifyCamelContextStarting(EventHelper.java:70)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:2939)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:175)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2812)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2808)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2831)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2808)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2777)
	at org.apache.camel.spring.SpringCamelContext.maybeStart(SpringCamelContext.java:270)
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:136)
	at org.apache.camel.spring.CamelContextFactoryBean.onApplicationEvent(CamelContextFactoryBean.java:340)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:778)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.wildfly.extension.camel.SpringCamelContextFactory.createCamelContextList(SpringCamelContextFactory.java:113)
	at org.wildfly.extension.camel.SpringCamelContextFactory.createCamelContextList(SpringCamelContextFactory.java:74)
	at org.wildfly.extension.camel.deployment.CamelContextCreateProcessor.deploy(CamelContextCreateProcessor.java:58)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tdiesler** [comment]
ServiceController.setMode(Mode.REMOVE) triggers an async service removal routine. In jboss-msc, you cannot reliably add a service with a given name, remove it and add it again.

The remove code is called - so its not a general issue. I guess what we can do is avoid duplicate context names in our test suites.
