### ISSUE TITLE
Infinispan component incompatible with wildfly

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1137]
camel-2.17 comes with infinispan-8.2
wildfly-10.0 comes with  infinispan-8.1

CrossRef: https://issues.jboss.org/browse/WFLY-6363

**Comment by tdiesler** [comment]
An alternative inifispan module would not integrate with the server modules

```
Caused by: java.lang.IllegalArgumentException: Can not set org.infinispan.manager.CacheContainer field org.wildfly.camel.test.infinispan.InfinispanIntegrationTest.cacheContainer to org.jboss.as.clustering.infinispan.DefaultCacheContainer
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.jboss.weld.injection.FieldResourceInjection.injectMember(FieldResourceInjection.java:62)
	at org.jboss.weld.injection.AbstractResourceInjection.injectResourceReference(AbstractResourceInjection.java:63)
	at org.jboss.weld.util.Beans.injectEEFields(Beans.java:351)
	at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
	at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)
	at org.jboss.arquillian.testenricher.cdi.CDIInjectionEnricher.injectNonContextualInstance(CDIInjectionEnricher.java:145)
	at org.jboss.arquillian.testenricher.cdi.CDIInjectionEnricher.injectClass(CDIInjectionEnricher.java:125)
```

**Comment by tdiesler** [comment]
Done
