### ISSUE TITLE
CXF Consumer Endpoints trigger IllegalStateException on server shutdown

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1173]
Probably because the Undertow 'default-host' service is stopped before the camel context....

```
08:58:56,891 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0019: Host default-host stopping
08:58:56,893 INFO  [org.apache.camel.spring.SpringCamelContext] (MSC service thread 1-5) Apache Camel 2.17.0 (CamelContext: cxfrs-camel-context) is shutting down
08:58:56,893 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
08:58:56,894 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (MSC service thread 1-5) Starting to graceful shutdown 2 routes (timeout 300 seconds)
08:58:56,897 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0019: Stopped Driver service with driver-name = h2
08:58:56,904 WARN  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (cxfrs-camel-context) thread #0 - ShutdownTask) Error occurred while shutting down route: Consumer[cxfrs://bean:cxfConsumer]. This exception will be ignored.: java.lang.IllegalStateException
	at org.jboss.msc.value.InjectedValue.getValue(InjectedValue.java:47)
	at org.wildfly.extension.undertow.Host.unregisterDeployment(Host.java:199)
	at org.apache.cxf.transport.undertow.wildfly.WildflyHTTPServerEngine.removeServant(WildflyHTTPServerEngine.java:84)
	at org.apache.cxf.transport.undertow.UndertowHTTPDestination.deactivate(UndertowHTTPDestination.java:160)
	at org.apache.cxf.transport.AbstractObservable.setMessageObserver(AbstractObservable.java:65)
	at org.apache.cxf.endpoint.ServerImpl.stop(ServerImpl.java:174)
	at org.apache.camel.component.cxf.jaxrs.CxfRsConsumer.doStop(CxfRsConsumer.java:55)
	at org.apache.camel.support.ServiceSupport.stop(ServiceSupport.java:102)
	at org.apache.camel.util.ServiceHelper.stopService(ServiceHelper.java:142)
	at org.apache.camel.impl.DefaultShutdownStrategy.shutdownNow(DefaultShutdownStrategy.java:381)
	at org.apache.camel.impl.DefaultShutdownStrategy$ShutdownTask.run(DefaultShutdownStrategy.java:575)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tdiesler** [comment]
I've run both the WS and RS consumer tests a couple of times & have not been seeing this any more

```
$ mvn clean install -Dtest=CXFRSConsumerIntegrationTest
$ mvn clean install -Dtest=CXFWSConsumerIntegrationTest
```
