### ISSUE TITLE
Add support for Spring based CamelContext injection

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1215]
[15:47:25]  <astefanutti>	tdiesler: OK that is supposed to be addressed with http://camel.apache.org/cdi.html#CDI-CamelXMLconfigurationimport

**Comment by tdiesler** [comment]
Done

**Comment by tdiesler** [comment]
Currently running into this

```
15:12:48,371 WARN  [org.apache.camel.management.DefaultManagementLifecycleStrategy] (MSC service thread 1-4) This CamelContext(contextG) will be registered using the name: contextG-1 due to clash with an existing name already registered in MBeanServer.
15:12:48,378 WARN  [org.apache.camel.util.EventHelper] (MSC service thread 1-4) Error notifying event Starting CamelContext: contextG. This exception will be ignored. : org.jboss.msc.service.DuplicateServiceException: Service jboss.naming.context.java.jboss.camel.context.contextG is already registered
	at org.jboss.msc.service.ServiceRegistrationImpl.setInstance(ServiceRegistrationImpl.java:158)
	at org.jboss.msc.service.ServiceControllerImpl.startInstallation(ServiceControllerImpl.java:235)
	at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:768)
	at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
	at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
	at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:317)
	at org.wildfly.extension.camel.service.CamelContextBindingService.addService(CamelContextBindingService.java:65)
	at org.wildfly.extension.camel.CamelCoreSubsystemExtension.addCamelContext(CamelCoreSubsystemExtension.java:67)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl$2.accept(CamelContextRegistryService.java:255)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl$2.accept(CamelContextRegistryService.java:252)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:891)
	at org.wildfly.extension.camel.parser.SubsystemState.processExtensions(SubsystemState.java:95)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl.addCamelContext(CamelContextRegistryService.java:252)
	at org.wildfly.extension.camel.service.CamelContextRegistryService$CamelContextRegistryImpl$1.notify(CamelContextRegistryService.java:228)
	at org.apache.camel.util.EventHelper.doNotifyEvent(EventHelper.java:805)
	at org.apache.camel.util.EventHelper.notifyCamelContextStarting(EventHelper.java:70)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3084)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:182)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2957)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2953)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2976)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2953)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2920)
	at org.apache.camel.impl.DefaultCamelContext$Proxy$_$$_WeldClientProxy.start(Unknown Source)
	at org.apache.camel.cdi.CdiCamelExtension.afterDeploymentValidation(CdiCamelExtension.java:422)
```

**Comment by tdiesler** [comment]
Currently @ImportResource does not support a resource name that also triggers subsystem processing of that resource

**Comment by tdiesler** [comment]
Done
