### ISSUE TITLE
jboss.persistenceunit.\"camel-jpa-test.jar#account\".__FIRST_PHASE__ is missing

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-extras/wildfly-camel#1216]
During the Arquillian deployment phase of a Camel CDI & JPA project, I get this error 

Version of Wildfly used : 9.0.2.Final
Wildfly : 3.3.0

Here is the persistence.xml file used

````
<persistence version="2.0"
             xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="
        http://java.sun.com/xml/ns/persistence
        http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">

    <persistence-unit name="account">
        <jta-data-source>java:jboss/datasources/AccountDS</jta-data-source>
        <class>org.jboss.fuse.persistence.jpa.model.Account</class>
        <properties>
            <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
            <property name="hibernate.show_sql" value="true"/>
        </properties>
    </persistence-unit>
</persistence>

````
Error 

```
18:28:19,407 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0027: Starting deployment of "camel-jpa-test.jar" (runtime-name: "camel-jpa-test.jar")
18:28:19,427 INFO  [org.jboss.as.jpa] (MSC service thread 1-8) WFLYJPA0002: Read persistence.xml for account
18:28:19,433 INFO  [org.wildfly.extension.camel] (MSC service thread 1-1) @CamelAware annotation found
18:28:19,457 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-5) WFLYSRV0018: Deployment "deployment.camel-jpa-test.jar" is using a private module ("org.wildfly.security.manager:main") which may be changed or removed in future versions without notice.
18:28:19,471 INFO  [org.jboss.weld.deployer] (MSC service thread 1-8) WFLYWELD0003: Processing weld deployment camel-jpa-test.jar
18:28:19,602 WARN  [org.jboss.weld.deployer] (MSC service thread 1-8) WFLYWELD0012: Warning while parsing jar:file:/Users/chmoulli/.m2/repository/org/apache/camel/camel-cdi/2.16.2/camel-cdi-2.16.2.jar!/META-INF/beans.xml:18 cvc-elt.1.a: Cannot find the declaration of element 'beans'.
18:28:19,644 INFO  [org.hibernate.validator.internal.util.Version] (MSC service thread 1-8) HV000001: Hibernate Validator 5.1.3.Final
18:28:19,715 INFO  [org.apache.deltaspike.core.util.ProjectStageProducer] (MSC service thread 1-8) Computed the following DeltaSpike ProjectStage: Production
18:28:19,742 INFO  [org.jboss.weld.deployer] (MSC service thread 1-4) WFLYWELD0006: Starting Services for CDI deployment: camel-jpa-test.jar
18:28:19,772 INFO  [org.jboss.weld.Version] (MSC service thread 1-4) WELD-000900: 2.2.16 (SP1)
18:28:19,780 INFO  [org.jboss.weld.deployer] (MSC service thread 1-8) WFLYWELD0009: Starting weld service for deployment camel-jpa-test.jar
18:28:19,780 INFO  [org.jboss.as.arquillian] (MSC service thread 1-4) Arquillian deployment detected: ArquillianConfig[service=jboss.arquillian.config."camel-jpa-test.jar",unit=camel-jpa-test.jar,tests=[org.jboss.fuse.persistence.jpa.JPACamelWildflyTest]]
18:28:19,907 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 3) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "camel-jpa-test.jar")]) - failure description: {"WFLYCTL0180: Services with missing/unavailable dependencies" => [
    "jboss.persistenceunit.\"camel-jpa-test.jar#account\".__FIRST_PHASE__ is missing [jboss.naming.context.java.jboss.datasources.AccountDS]",
    "jboss.persistenceunit.\"camel-jpa-test.jar#account\" is missing [jboss.naming.context.java.jboss.datasources.AccountDS]"
]}
18:28:19,908 ERROR [org.jboss.as.server] (management-handler-thread - 3) WFLYSRV0021: Deploy of deployment "camel-jpa-test.jar" was rolled back with the following failure message: 
{"WFLYCTL0180: Services with missing/unavailable dependencies" => [
    "jboss.persistenceunit.\"camel-jpa-test.jar#account\".__FIRST_PHASE__ is missing [jboss.naming.context.java.jboss.datasources.AccountDS]",
    "jboss.persistenceunit.\"camel-jpa-test.jar#account\" is missing [jboss.naming.context.java.jboss.datasources.AccountDS]"
]}
18:28:19,913 INFO  [org.jboss.weld.deployer] (MSC service thread 1-1) WFLYWELD0010: Stopping weld service for deployment camel-jpa-test.jar
18:28:19,943 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment camel-jpa-test.jar (runtime-name: camel-jpa-test.jar) in 35ms
18:28:19,944 INFO  [org.jboss.as.controller] (management-handler-thread - 3) WFLYCTL0183: Service status report
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."camel-jpa-test.jar".WeldBootstrapService (missing) dependents: [service jboss.deployment.unit."camel-jpa-test.jar".CdiValidatorFactoryService, service jboss.deployment.unit."camel-jpa-test.jar".WeldStartService] 
      service jboss.deployment.unit."camel-jpa-test.jar".WeldStartService (missing) dependents: [service jboss.deployment.unit."camel-jpa-test.jar".CdiValidatorFactoryService] 
      service jboss.deployment.unit."camel-jpa-test.jar".beanmanager (missing) dependents: [service jboss.persistenceunit."camel-jpa-test.jar#account"] 
      service jboss.deployment.unit."camel-jpa-test.jar".jndiDependencyService (missing) dependents: [service jboss.deployment.unit."camel-jpa-test.jar".WeldStartService] 
      service jboss.naming.context.java.jboss.datasources.AccountDS (missing) dependents: [service jboss.persistenceunit."camel-jpa-test.jar#account".__FIRST_PHASE__, service jboss.persistenceunit."camel-jpa-test.jar#account"] 
      service jboss.persistenceunit."camel-jpa-test.jar#account" (missing) dependents: [service jboss.deployment.unit."camel-jpa-test.jar".deploymentCompleteService, service jboss.deployment.unit."camel-jpa-test.jar".WeldStartService] 

[                          main] ArchiveDeployer                WARN  Cannot undeploy: camel-jpa-test.jar
org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper$ServerDeploymentException: java.lang.Exception: "WFLYCTL0216: Management resource '[(\"deployment\" => \"camel-jpa-test.jar\")]' not found"
        at org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper.undeploy(ServerDeploymentHelper.java:114)
        at org.jboss.as.arquillian.container.ArchiveDeployer.undeploy(ArchiveDeployer.java:111)
        at org.jboss.as.arquillian.container.CommonDeployableContainer.undeploy(CommonDeployableContainer.java:242)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$4.call(ContainerDeployController.java:205)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$4.call(ContainerDeployController.java:185)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
        at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.undeploy(ContainerDeployController.java:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
```

**Comment by cmoulliard** [comment]
The workaround that I'm using for the moment is :  

- Create a Wildfly Datasource xml config file 

```
<?xml version="1.0" encoding="UTF-8"?>
<datasources xmlns="http://www.jboss.org/ironjacamar/schema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="
        http://www.jboss.org/ironjacamar/schema
        http://docs.jboss.org/ironjacamar/schema/datasources_1_0.xsd">
    <datasource enabled="true"
                jndi-name="java:jboss/datasources/AccountDS"
                pool-name="ArquillianEmbeddedH2Pool">
        <connection-url>jdbc:h2:mem:account;DB_CLOSE_DELAY=-1</connection-url>
        <driver>h2</driver>
    </datasource>
</datasources>
```

- Pass it as Resource to create the JAR file to be deployed

```
        archive.addAsManifestResource("org/jboss/fuse/persistence/jpa/jbossas-ds.xml");
```

Questions : 

1) Can we add it as a subsystem instead of creating a DS XML File ?

```
<subsystem xmlns="urn:jboss:domain:datasources:1.0">
    <datasources>
        <datasource jndi-name="java:jboss/datasources/ExampleDS" pool-name="ExampleDS">
            <connection-url>jdbc:h2:mem:test;DB_CLOSE_DELAY=-1</connection-url>
            <driver>h2</driver>
...
        </datasource>
....
```

2) No DS Datasource is defined for this example but apparently that works (https://github.com/wildfly-extras/wildfly-camel/blob/ed9c2c7d95ef30fd4aa457f423585b64e9a17da4/itests/standalone/basic/src/main/java/org/wildfly/camel/test/jpa/UserManagedTransactionIntegrationTest.java#L64-L64). Why ?

**Comment by tdiesler** [comment]
I believe our examples use the default data source. If you wish to bring the sever in a certain setup state before the test can run, have a look at JMSIntegrationTest for the use of ServerSetupTask.

**Comment by cmoulliard** [comment]
You are right. You are using the ExampleDS default datasource packaged in every standalone.xml config file. so, you don't have to add/create an additional ds config file.
