### ISSUE TITLE
InaccessibleObjectException in RubyToJavaInvoker

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1263]
```
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+128)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+128, mixed mode)
```

```
Caused by: java.lang.reflect.InaccessibleObjectException: Cannot make a non-public member of class java.lang.reflect.AccessibleObject accessible
    at jdk.internal.reflect.Reflection.throwInaccessibleObjectException(java.base@9-ea/Reflection.java:414)
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-ea/AccessibleObject.java:190)
    at java.lang.reflect.Method.checkCanSetAccessible(java.base@9-ea/Method.java:191)
    at java.lang.reflect.AccessibleObject.setAccessible(java.base@9-ea/AccessibleObject.java:110)
    at org.jruby.java.invokers.RubyToJavaInvoker.trySetAccessible(RubyToJavaInvoker.java:184)
    at org.jruby.java.invokers.MethodInvoker.<init>(MethodInvoker.java:14)
    at org.jruby.java.invokers.StaticMethodInvoker.<init>(StaticMethodInvoker.java:17)
```

CrossRef: https://issues.apache.org/jira/browse/CAMEL-10188

**Comment by tdiesler** [comment]
This seems to be caught es a SecurityException

```
    static void trySetAccessible(AccessibleObject[] accObjs) {
        if (!Ruby.isSecurityRestricted()) {
            try {
                AccessibleObject.setAccessible(accObjs, true);
            } catch(SecurityException e) {}
        }
    }
``` 

which [InaccessibleObjectException](http://download.java.net/java/jdk9/docs/api/java/lang/reflect/InaccessibleObjectException.html) is not
