### ISSUE TITLE
Cannot build archetypes on Windows

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1266]
CrossRef: https://issues.apache.org/jira/browse/MNG-6072

```
[INFO] --- maven-archetype-plugin:2.2:integration-test (default-integration-test) @ wildfly-camel-archetype-cdi ---
[INFO] Processing Archetype IT project: test-archetype-cdi
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: wildfly-camel-archetype-cdi:4.2.0-SNAPSHOT
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: artifactId, Value: wildfly-camel-archetype-cdi-test
[INFO] Parameter: version, Value: 1.0
[INFO] Parameter: package, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: packageInPathFormat, Value: org/wildfly/camel/archetype/test
[INFO] Parameter: version-wildfly-arquillian, Value: 1.0.2.Final
[INFO] Parameter: version-jboss-arquillian, Value: 1.1.10.Final
[INFO] Parameter: version-wildfly, Value: 10.0.0.Final
[INFO] Parameter: groupId, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: version-junit, Value: 4.11
[INFO] Parameter: version, Value: 1.0
[INFO] Parameter: version-maven-war-plugin, Value: 2.5
[INFO] Parameter: version-apache-camel, Value: 2.17.2
[INFO] Parameter: package, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: version-wildfly-maven-plugin, Value: 1.1.0.Alpha7
[INFO] Parameter: version-maven-compiler-plugin, Value: 3.1
[INFO] Parameter: artifactId, Value: wildfly-camel-archetype-cdi-test
[INFO] Parameter: version-wildfly-camel, Value: 4.2.0-SNAPSHOT
[INFO] Parameter: version-maven-surefire-plugin, Value: 2.18.1
[INFO] project created from Archetype in dir: C:\Users\Administrator\git\wildfly-camel\archetypes\archetype-cdi\target\t
est-classes\projects\test-archetype-cdi\project\wildfly-camel-archetype-cdi-test
[INFO] Invoking post-archetype-generation goals: verify -Parq-managed -Djboss.home=C:\\Users\\Administrator\\git\\wildfl
y-camel\\archetypes\\archetype-cdi\\target\\wildfly-10.0.0.Final -Dserver.config=standalone.xml

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.142 s
[INFO] Finished at: 2016-07-29T11:30:52+02:00
[INFO] Final Memory: 65M/762M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration
-test) on project wildfly-camel-archetype-cdi:
[ERROR] Archetype IT 'test-archetype-cdi' failed: Cannot run additions goals.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-
plugin:2.2:integration-test (default-integration-test) on project wildfly-camel-archetype-cdi:
Archetype IT 'test-archetype-cdi' failed: Cannot run additions goals.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException:
Archetype IT 'test-archetype-cdi' failed: Cannot run additions goals.
        at org.apache.maven.archetype.mojos.IntegrationTestMojo.execute(IntegrationTestMojo.java:268)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
PS C:\Users\Administrator\git\wildfly-camel\archetypes\archetype-cdi>
```

**Comment by jamesnetherton** [comment]
Tested with maven-archetype-plugin 2.5-SNAPSHOT and everything works fine.

Blocked pending 2.5 plugin release.

**Comment by jamesnetherton** [comment]
Note: This affects builds performed with Maven 3.3.x
