### ISSUE TITLE
Spring CXF context cannot see javax/annotation/Resource

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1267]
```
Caused by: java.lang.ClassNotFoundException: javax.annotation.Resource from [Module "org.springframework.context:main" from local module loader @6b67034 (finder: local module finder @16267862 (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.Final/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.Final/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.Final/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	... 51 more
```

**Comment by tdiesler** [comment]
done
