### ISSUE TITLE
Cannot compile MVEL template

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1340]
Seen on JDK9-ea137

```
Caused by: java.lang.ExceptionInInitializerError
	at org.mvel2.templates.TemplateCompiler.captureOrbToken(TemplateCompiler.java:305)
	at org.mvel2.templates.TemplateCompiler.compileFrom(TemplateCompiler.java:114)
	at org.mvel2.templates.TemplateCompiler.compile(TemplateCompiler.java:82)
	at org.mvel2.templates.TemplateCompiler.compileTemplate(TemplateCompiler.java:360)
	at org.apache.camel.component.mvel.MvelEndpoint.onExchange(MvelEndpoint.java:115)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	... 163 more
Caused by: java.lang.NumberFormatException: For input string: "9-e"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(java.base@9-ea/FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseDouble(java.base@9-ea/FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(java.base@9-ea/Double.java:539)
	at org.mvel2.util.ParseTools.<clinit>(ParseTools.java:84)
	... 170 more
```

CrossRef: https://github.com/mvel/mvel/issues/106

**Comment by tdiesler** [comment]
Caused by invalid usage of camel-2.17.x
