### ISSUE TITLE
javax/net/ssl/SSLSocket missed for camel-smpp

### ISSUE THREAD

**Issue by msiniy** [wildfly-extras/wildfly-camel#1358]
Hi!
I'm running wildfly-10 with wildfly-camel-patch 4.2.0. When  I tried to define a route with camel-smpp component I got NoClassDefFoundError exception:
```
....
org.apache.camel.cdi.CdiCamelExtension.afterDeploymentValidation(CdiCamelExtension.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	... 20 more
Caused by: java.lang.ClassNotFoundException: javax.net.ssl.SSLSocket from [Module \"org.apache.camel.component.smpp:main\" from local module loader @282ba1e (finder: local module finder @13b6d03 (roots: /home/siniy/distr/wildfly-10.0.0.Final/modules,/home/siniy/distr/wildfly-10.0.0.Final/modules/system/layers/fuse,/home/siniy/distr/wildfly-10.0.0.Final/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	... 77 more
"}}
```

My code raised error:
```
@Startup
@ApplicationScoped
@ContextName("camel-smpp-client")
public class SMPPClientBuilder extends RouteBuilder {
    
    public final static String SMPP_ENDPOINT = "smpp://guest@localhost:999";

    @Override
    public void configure() throws Exception {
        from("direct:send").to(SMPP_ENDPOINT);        
    }
}
```
I found that this may be fixed by adding the dependency from javax.api to the smpp component module. 
So, when I added a line `<module name="javax.api"/> ` to the dependencies section in file `modules/system/layers/fuse/org/apache/camel/component/smpp/main/module.xml` the problem had gone.

**Comment by jamesnetherton** [comment]
Thanks for reporting. Will be fixed in the next release.
