### ISSUE TITLE
Ruby script may see invalid request object

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1395]
A ruby script like this 

```
body = $request.getBody() 
$request.setBody("Hello " + body);
```
may (often enough) lead to

```
[0m[0m10:31:38,576 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-2) Apache Camel 2.19.0-SNAPSHOT (CamelContext: camel-146) is starting
[0m[0m10:31:38,577 INFO  [org.apache.camel.management.ManagedManagementStrategy] (pool-3-thread-2) JMX is enabled
[0m[0m10:31:38,582 INFO  [org.wildfly.extension.camel] (pool-3-thread-2) Camel context starting: camel-146
[0m[0m10:31:38,582 INFO  [org.wildfly.extension.camel] (MSC service thread 1-7) Bound camel naming object: java:jboss/camel/context/camel-146
[0m[0m10:31:38,586 INFO  [org.apache.camel.impl.converter.DefaultTypeConverter] (pool-3-thread-2) Loaded 299 type converters
[0m[0m10:31:38,591 INFO  [org.apache.camel.impl.DefaultRuntimeEndpointRegistry] (pool-3-thread-2) Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
[0m[0m10:31:38,595 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-2) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[0m[0m10:31:38,598 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-2) Route: route135 started and consuming from: direct://start
[0m[0m10:31:38,599 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-2) Total 1 routes, of which 1 are started.
[0m[0m10:31:38,599 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-2) Apache Camel 2.19.0-SNAPSHOT (CamelContext: camel-146) started in 0.023 seconds
[0m[31m10:31:42,268 ERROR [stderr] (pool-3-thread-2) NoMethodError: undefined method `getBody' for nil:NilClass
[0m[31m10:31:42,268 ERROR [stderr] (pool-3-thread-2)   (root) at <script>:1
[0m[31m10:31:42,271 ERROR [org.apache.camel.processor.DefaultErrorHandler] (pool-3-thread-2) Failed delivery for (MessageId: ID-localhost-55830-1479720512348-145-1 on ExchangeId: ID-localhost-55830-1479720512348-145-2). Exhausted after delivery attempt: 1 caught: org.apache.camel.builder.script.ScriptEvaluationException: Failed to evaluate: ruby: body = $request.getBody() 
$request.setBody("Hello " + body);. Cause: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `getBody' for nil:NilClass

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route135          ] [route135          ] [direct://start                                                                ] [      3671]
[route135          ] [process11         ] [Processor@0x10587b5d                                                          ] [      3671]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.builder.script.ScriptEvaluationException: Failed to evaluate: ruby: body = $request.getBody() 
$request.setBody("Hello " + body);. Cause: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `getBody' for nil:NilClass
	at org.apache.camel.builder.script.ScriptBuilder.createScriptEvaluationException(ScriptBuilder.java:547)
	at org.apache.camel.builder.script.ScriptBuilder.evaluateScript(ScriptBuilder.java:416)
	at org.apache.camel.builder.script.ScriptBuilder.process(ScriptBuilder.java:181)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:529)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:497)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:365)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:497)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:260)
	at org.apache.camel.impl.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:337)
	at org.wildfly.camel.test.script.ScriptIntegrationTest.scriptProcessing(ScriptIntegrationTest.java:100)
	at org.wildfly.camel.test.script.ScriptIntegrationTest.testRuby(ScriptIntegrationTest.java:76)
...
Caused by: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `getBody' for nil:NilClass
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:132)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
	at org.apache.camel.builder.script.ScriptBuilder.runScript(ScriptBuilder.java:469)
	at org.apache.camel.builder.script.ScriptBuilder.doEvaluateScript(ScriptBuilder.java:428)
	at org.apache.camel.builder.script.ScriptBuilder.evaluateScript(ScriptBuilder.java:409)
	... 151 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `getBody' for nil:NilClass
	at RUBY.(root)(<script>:1)

```

**Comment by tdiesler** [comment]
Related to: https://issues.apache.org/jira/browse/CAMEL-10477
