### ISSUE TITLE
Add support for component hbase

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1441]
http://camel.apache.org/hbase.html

**Comment by jamesnetherton** [comment]
Maybe we hold on Integrating this. It's super messy. There's a few issues:

* HBase 1.x only works with a Guava version <= 1.14. But WildFly has 1.18. API incompatibilities result in:

 ```
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
		at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:601)
		at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:585)
		at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:564)
		at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
		at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1211)
		at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1178)
		at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.relocateRegion(ConnectionManager.java:1152)
		at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1357)
		at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1181)
		at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:395)
		at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:344)
		at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:238)
		at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:190)
		at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1422)
		at org.apache.hadoop.hbase.client.HTable.close(HTable.java:1458)
		at org.apache.camel.component.hbase.HBaseProducer.process(HBaseProducer.java:101) 
```

* Testing is a nightmare. I wanted to add the HBase embedded server to WFC but it requires all kinds of Maven exclusion hacks because Camel forces the version of Hadoop to a higher version than what HBase builds against

We could add a custom guava slot for 12.0 but it complicates the module defs somewhat, given that there's quite a few things that depend on guava (which need > 12.0).

**Comment by tdiesler** [comment]
Found 4 [matching posts](http://camel.465427.n5.nabble.com/template/NamlServlet.jtp?macro=search_page&node=465428&query=subject%3A+hbase&days=700) for subject: hbase in Camel - Users within 700 days

**Comment by jamesnetherton** [comment]
Unfortunately, the HBase libraries have a [hack](https://github.com/apache/hbase/blob/rel/1.2.1/hbase-protocol/src/main/java/com/google/protobuf/HBaseZeroCopyByteString.java) where they place one of their own classes under the `com.google.protobuf` package. This results in a warning when the HBase endpoint is initialized:

```
12:24:54,901 WARN  [org.jboss.modules] (hconnection-0x44235346-metaLookup-shared--pool1-t1) Failed to define class com.google.protobuf.HBaseZeroCopyByteString in Module "org.apache.hbase:main" from local module loader @1ee807c6 (finder: local module finder @76a4d6c (roots: /home/james/Projects/git/fork/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules,/home/james/Projects/git/fork/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules/system/layers/fuse,/home/james/Projects/git/fork/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules/system/layers/base)): java.lang.NoClassDefFoundError: Failed to link com/google/protobuf/HBaseZeroCopyByteString (Module "org.apache.hbase:main" from local module loader @1ee807c6 (finder: local module finder @76a4d6c (roots: /home/james/Projects/git/fork/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules,/home/james/Projects/git/fork/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules/system/layers/fuse,/home/james/Projects/git/fork/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules/system/layers/base))): com/google/protobuf/LiteralByteString
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:446)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
	at org.jboss.modules.Module.loadModuleClass(Module.java:606)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at org.apache.hadoop.hbase.util.ByteStringer.<clinit>(ByteStringer.java:44)
	at org.apache.hadoop.hbase.protobuf.RequestConverter.buildRegionSpecifier(RequestConverter.java:1037)
	at org.apache.hadoop.hbase.protobuf.RequestConverter.buildScanRequest(RequestConverter.java:488)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:194)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:180)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:360)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:334)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


```
This does not happen in the latest 1.2.6 release, hence I opened a Camel ticket to upgrade in 2.20.x: 

https://issues.apache.org/jira/browse/CAMEL-11676
