### ISSUE TITLE
Intermittent failure of HystrixIntegrationTest

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1507]
Seems the Hystrix fallback response is unexpectedly returned instead of the expected value from the HTTP endpoint. 
```
org.junit.ComparisonFailure: expected:<Hello [Kermit]> but was:<Hello [World]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.wildfly.camel.test.hystrix.HystrixIntegrationTest.testHystrixCircuitBreakerFallback(HystrixIntegrationTest.java:117)
```

**Comment by tdiesler** [comment]
Does not show any more
https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel-stability/
