### ISSUE TITLE
Cannot allocate class io.nats.client.ServerInfo

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1513]
```
SEVERE: Failed: org.wildfly.camel.test.nats.NatsIntegrationTest.testNatsRoutes
java.lang.RuntimeException: Unable to invoke no-args constructor for class io.nats.client.ServerInfo. Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at io.nats.client.ServerInfo.createFromWire(ServerInfo.java:84)
	at io.nats.client.ConnectionImpl.processInfo(ConnectionImpl.java:762)
	at io.nats.client.ConnectionImpl.processExpectedInfo(ConnectionImpl.java:707)
	at io.nats.client.ConnectionImpl.processConnectInit(ConnectionImpl.java:652)
	at io.nats.client.ConnectionImpl.connect(ConnectionImpl.java:399)
	at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:468)
	at io.nats.client.ConnectionFactory.createConnection(ConnectionFactory.java:458)
	at org.apache.camel.component.nats.NatsConsumer.getConnection(NatsConsumer.java:113)
	at org.apache.camel.component.nats.NatsConsumer.doStart(NatsConsumer.java:67)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3389)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRouteConsumers(DefaultCamelContext.java:3706)
	at org.apache.camel.impl.DefaultCamelContext.doStartRouteConsumers(DefaultCamelContext.java:3642)
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3562)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3326)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3180)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:190)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2975)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2971)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2994)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2971)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2909)
	at org.wildfly.camel.test.nats.NatsIntegrationTest.testNatsRoutes(NatsIntegrationTest.java:89)
```

CrossRef: https://issues.apache.org/jira/browse/CAMEL-10590

**Comment by tdiesler** [comment]
The gson module needs:

```
    <module name="sun.jdk">
      <imports>
        <include path="sun/misc/Unsafe" />
      </imports>
    </module>
```
