### ISSUE TITLE
Cassandra crashes build on AIX

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1622]
https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-master-aix

```
Running org.wildfly.camel.test.cassandra.CassandraIntegrationTest
Feb 15, 2017 10:21:10 AM org.jboss.arquillian.container.test.impl.client.deployment.AnnotationDeploymentScenarioGenerator logWarningIfArchiveHasUnexpectedFileExtension
WARNING: Deployment archive of type JavaArchiveImpl has been given an unexpected file extension. Archive name: cassandra-tests, deployment name: _DEFAULT_. It might not be wrong, but the container will rely on the given file extension, the archive type is only a description of a certain structure.
2017-02-15 10:21:10 WARN  [org.apache.cassandra.config.DatabaseDescriptor] (main) - Only 33774 MB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
2017-02-15 10:21:10 WARN  [org.apache.cassandra.utils.CLibrary] (COMMIT-LOG-ALLOCATOR) - JNA link failure, one or more native method will be unavailable.
2017-02-15 10:21:10 WARN  [org.apache.cassandra.utils.BackgroundActivityMonitor] (ScheduledTasks:1) - Couldn't open /proc/stats
2017-02-15 10:21:10 WARN  [org.apache.cassandra.service.StartupChecks] (pool-1-thread-1) - jemalloc shared library could not be preloaded to speed up memory allocations
2017-02-15 10:21:10 WARN  [org.apache.cassandra.service.StartupChecks] (pool-1-thread-1) - JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info.
2017-02-15 10:21:10 ERROR [org.apache.cassandra.service.StartupChecks] (pool-1-thread-1) - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
2017-02-15 10:21:10 WARN  [org.apache.cassandra.service.StartupChecks] (pool-1-thread-1) - Non-Oracle JVM detected.  Some features, such as immediate unmap of compacted SSTables, may not work as intended
Exception (java.lang.UnsatisfiedLinkError) encountered during startup: java/util/zip/CRC32.updateByteBuffer(IJII)I
java.lang.UnsatisfiedLinkError: java/util/zip/CRC32.updateByteBuffer(IJII)I
	at java.util.zip.CRC32.update(CRC32.java:120)
	at org.apache.cassandra.utils.FBUtilities.updateChecksum(FBUtilities.java:651)
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:283)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:498)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:399)
	at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:202)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:214)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:228)
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternalWithoutCondition(ModificationStatement.java:553)
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternal(ModificationStatement.java:547)
	at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:295)
	at org.apache.cassandra.db.SystemKeyspace.removeTruncationRecord(SystemKeyspace.java:622)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:519)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:495)
	at org.apache.cassandra.schema.LegacySchemaMigrator.lambda$unloadLegacySchemaTables$278(LegacySchemaMigrator.java:136)
	at org.apache.cassandra.schema.LegacySchemaMigrator$$Lambda$73.00000000251E9370.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:86)
	at org.apache.cassandra.schema.LegacySchemaMigrator.unloadLegacySchemaTables(LegacySchemaMigrator.java:136)
	at org.apache.cassandra.schema.LegacySchemaMigrator.migrate(LegacySchemaMigrator.java:82)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:223)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
2017-02-15 10:21:17 ERROR [org.apache.cassandra.service.CassandraDaemon] (pool-1-thread-1) - Exception encountered during startup
java.lang.UnsatisfiedLinkError: java/util/zip/CRC32.updateByteBuffer(IJII)I
	at java.util.zip.CRC32.update(CRC32.java:120)
	at org.apache.cassandra.utils.FBUtilities.updateChecksum(FBUtilities.java:651)
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:283)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:498)
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:399)
	at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:202)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:214)
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:228)
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternalWithoutCondition(ModificationStatement.java:553)
	at org.apache.cassandra.cql3.statements.ModificationStatement.executeInternal(ModificationStatement.java:547)
	at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:295)
	at org.apache.cassandra.db.SystemKeyspace.removeTruncationRecord(SystemKeyspace.java:622)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:519)
	at org.apache.cassandra.db.ColumnFamilyStore.invalidate(ColumnFamilyStore.java:495)
	at org.apache.cassandra.schema.LegacySchemaMigrator.lambda$unloadLegacySchemaTables$278(LegacySchemaMigrator.java:136)
	at org.apache.cassandra.schema.LegacySchemaMigrator$$Lambda$73.00000000251E9370.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:86)
	at org.apache.cassandra.schema.LegacySchemaMigrator.unloadLegacySchemaTables(LegacySchemaMigrator.java:136)
	at org.apache.cassandra.schema.LegacySchemaMigrator.migrate(LegacySchemaMigrator.java:82)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:223)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
[0m10:21:17,018 INFO  [org.jbos
Results :

Tests run: 16, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Wildfly Camel ...................................... SUCCESS [  0.903 s]
[INFO] Wildfly Camel :: Config ............................ SUCCESS [  3.551 s]
[INFO] WildFly Camel :: CXF Undertow ...................... SUCCESS [  1.583 s]
[INFO] Wildfly Camel :: Subsystem ......................... SUCCESS [  0.020 s]
[INFO] Wildfly Camel :: Subsystem :: Core ................. SUCCESS [  3.175 s]
[INFO] Wildfly Camel :: Subsystem :: CDI .................. SUCCESS [  0.962 s]
[INFO] Wildfly Camel :: Subsystem :: Security ............. SUCCESS [  0.719 s]
[INFO] Wildfly Camel :: Subsystem :: Undertow ............. SUCCESS [  0.953 s]
[INFO] Wildfly Camel :: Feature Pack ...................... SUCCESS [01:13 min]
[INFO] Wildfly Camel :: Catalog ........................... SUCCESS [02:08 min]
[INFO] Wildfly Camel :: Enricher .......................... SUCCESS [  0.557 s]
[INFO] Wildfly Camel :: Testsuite ......................... SUCCESS [  0.016 s]
[INFO] Wildfly Camel :: Testsuite :: Common ............... SUCCESS [  2.056 s]
[INFO] Wildfly Camel :: Testsuite :: Standalone ........... SUCCESS [  0.018 s]
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Smoke .. SUCCESS [02:08 min]
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Basic .. FAILURE [01:55 min]
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Extra .. SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Camel ................ SKIPPED
[INFO] Wildfly Camel :: Archetypes ........................ SKIPPED
[INFO] Wildfly Camel :: Archetypes :: CDI ................. SKIPPED
[INFO] Wildfly Camel :: Archetypes :: Spring .............. SKIPPED
[INFO] Wildfly Camel :: Docs .............................. SKIPPED
[INFO] Wildfly Camel :: Patch ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:45 min
[INFO] Finished at: 2017-02-15T10:21:30-05:00
[INFO] Final Memory: 302M/588M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project wildfly-camel-itests-standalone-basic: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/[*******]/workspace/wildfly-camel-master-aix/itests/standalone/basic && /usr/java8_64/jre/bin/java -jar /home/[*******]/workspace/wildfly-camel-master-aix/itests/standalone/basic/target/surefire/surefirebooter1654061892823175668.jar /home/[*******]/workspace/wildfly-camel-master-aix/itests/standalone/basic/target/surefire/surefire8145611884517579165tmp /home/[*******]/workspace/wildfly-camel-master-aix/itests/standalone/basic/target/surefire/surefire_43700466836981469613tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wildfly-camel-itests-standalone-basic
```

**Comment by mbicer00** [comment]
Hi  tdiesler,
this issue is resolved ? i meet with the same issue when i install the cassandra 3.11.1  on AIX.

it it resolved please share with me.

Regards.
