### ISSUE TITLE
ExecIntegrationTest fails on Windows

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1628]
https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-master-windows/7/testReport/junit/org.wildfly.camel.test.exec/ExecIntegrationTest/testExecProducer/

```
org.apache.camel.FailedToCreateRouteException: Failed to create route route68 at: >>> To[exec:cmd.exe?args=/C echo Hello Kermit
] <<< in route: Route(route68)[[From[direct:start]] -> [To[exec:cmd.exe?args... because of Failed to resolve endpoint: exec:cmd.exe?args=/C echo Hello Kermit
 due to: Illegal character in opaque part at index 44: exec:cmd.exe?args=/C%20echo%20Hello%20Kermit

	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.camel.util.URISupport.normalizeUri(URISupport.java:534)
	at org.apache.camel.impl.DefaultCamelContext.normalizeEndpointUri(DefaultCamelContext.java:694)
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:578)
	at org.apache.camel.util.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:79)
	at org.apache.camel.model.RouteDefinition.resolveEndpoint(RouteDefinition.java:211)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:108)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:114)
	at org.apache.camel.model.SendDefinition.resolveEndpoint(SendDefinition.java:62)
	at org.apache.camel.model.SendDefinition.createProcessor(SendDefinition.java:56)
	at org.apache.camel.model.ProcessorDefinition.makeProcessorImpl(ProcessorDefinition.java:545)
	at org.apache.camel.model.ProcessorDefinition.makeProcessor(ProcessorDefinition.java:506)
	at org.apache.camel.model.ProcessorDefinition.addRoutes(ProcessorDefinition.java:222)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:1068)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:196)
	at org.apache.camel.impl.DefaultCamelContext.startRoute(DefaultCamelContext.java:984)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:3401)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3132)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:183)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2961)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2957)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2980)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2957)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2924)
	at org.wildfly.camel.test.exec.ExecIntegrationTest.testExecProducer(ExecIntegrationTest.java:66)
```

**Comment by jamesnetherton** [comment]
I seem to remember hitting this some time back. Think I have a fix on a local branch somewhere which I forgot to push up.
