### ISSUE TITLE
SchematronIntegrationTest fails on Windows

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1629]
https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-master-windows/7/testReport/junit/org.wildfly.camel.test.schematron/SchematronIntegrationTest/testSchematronValidation/

```
org.apache.camel.FailedToCreateRouteException: Failed to create route route157: Route(route157)[[From[direct:start]] -> [To[schematron://sch... because of javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: I/O error reported by XML parser processing null: null
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:862)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:154)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTransformer(SaxonTransformerFactory.java:110)
	at org.apache.camel.component.schematron.processor.TemplatesFactory.getTemplates(TemplatesFactory.java:74)
	at org.apache.camel.component.schematron.SchematronEndpoint.doStart(SchematronEndpoint.java:147)
```

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-11074
