### ISSUE TITLE
SegmentationError with elasticsearch on AIX

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1632]

**Comment by jamesnetherton** [comment]
It's a JDK bug:

```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/ibm/lang/management/MemoryMXBeanImpl.getNonHeapMemoryUsageImpl(Native Method)
4XESTACKTRACE                at com/ibm/lang/management/MemoryMXBeanImpl.getNonHeapMemoryUsage(Bytecode PC:1)
4XESTACKTRACE                at org/elasticsearch/monitor/jvm/JvmInfo.<clinit>(JvmInfo.java:74)
4XESTACKTRACE                at org/elasticsearch/node/Node.<init>(Node.java:149)
4XESTACKTRACE                at org/elasticsearch/node/Node.<init>(Node.java:140)
4XESTACKTRACE                at org/elasticsearch/node/NodeBuilder.build(NodeBuilder.java:143)
4XESTACKTRACE                at org/elasticsearch/node/NodeBuilder.node(NodeBuilder.java:150)
4XESTACKTRACE                at org/wildfly/camel/test/elasticsearch/subA/ElasticSearchClientProducer.getClient(ElasticSearchClientProducer.java:49)
```

**Comment by jamesnetherton** [comment]
Debatable whether we should even pursue a fix for this. I'm yet to see any clear evidence that ES runs properly on AIX or is in any way supported.
