### ISSUE TITLE
Messaging subsystem JNDI bindings may not be available when an application starts

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1641]
A user was attempting to make use of the WildFly messaging subsystem via camel-jms.

```
<beans xmlns="http://www.springframework.org/schema/beans"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:jee="http://www.springframework.org/schema/jee"
      xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
      http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd
      http://www.springframework.org/schema/jee http://www.springframework.org/schema/jee/spring-jee.xsd">

    <camelContext xmlns="http://camel.apache.org/schema/spring" id="jms-camel-contenxt">
        <!-- routes -->
    </camelContext>
 
    <bean id="jmsComponent" class="org.apache.camel.component.jms.JmsComponent">
        <property name="connectionFactory" ref="jmsConnectionFactory"/>
    </bean>
 
    <jee:jndi-lookup id="jmsConnectionFactory" jndi-name="java:jboss/DefaultJMSConnectionFactory" />
</beans>
```

But on deployment, the JNDI lookup was failing. Below is a excerpt from the sever logs. Notice that `java:jboss/DefaultJMSConnectionFactory` is bound after the Spring camel context is instantiated. 

Weirdly, I cannot replicate this. But looking at when WildFly binds the JMS ConnectionFactory, it happens at [Phase.INSTALL](https://github.com/wildfly/wildfly/blob/02f2979d6e49bc4be48f61aa5319c980169e48ec/messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingSubsystemAdd.java#L79). But the Camel subsystem creates the Spring Camel context during [Phase.POST_MODULE](https://github.com/wildfly-extras/wildfly-camel/blob/86723b099ddf0668b189fe6c8e0e92a59156648d/subsystem/core/src/main/java/org/wildfly/extension/camel/parser/CamelSubsystemAdd.java#L105). So perhaps this explains why this problem can happen.

```
08:17:39,477 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "airtable-mapper-1.0.0.war" (runtime-name: "airtable-mapper-1.0.0.war")
08:17:39,478 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "airtable-1.0.0.war" (runtime-name: "airtable-1.0.0.war")
08:17:39,485 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "hawtio-wildfly-1.4.65.war" (runtime-name: "hawtio-wildfly-1.4.65.war")
08:17:44,369 INFO  [org.apache.activemq.artemis.core.server] (ServerService Thread Pool -- 66) AMQ221043: Protocol module found: [artemis-server]. Adding protocol support for: CORE
08:17:45,087 INFO  [org.wildfly.extension.camel] (MSC service thread 1-1) Camel context descriptors found
08:17:45,179 INFO  [org.apache.activemq.artemis.core.server] (ServerService Thread Pool -- 66) AMQ221007: Server is now live
08:17:45,184 INFO  [org.apache.activemq.artemis.core.server] (ServerService Thread Pool -- 66) AMQ221001: Apache ActiveMQ Artemis Message Broker version 1.1.0.wildfly-017 [nodeID=6299753d-f8d7-11e6-a342-63567e85a0b8]
08:17:45,291 INFO  [org.wildfly.extension.camel.SpringCamelContextFactory$1] (MSC service thread 1-2) Loading XML bean definitions from URL [vfs:/content/airtable-mapper-1.0.0.war/META-INF/jboss-camel-context.xml]
08:17:48,149 INFO  [org.springframework.context.support.GenericApplicationContext] (MSC service thread 1-1) Refreshing org.springframework.context.support.GenericApplicationContext@19038074: startup date [Wed Feb 22 08:17:48 UTC 2017]; root of context hierarchy
08:17:48,304 INFO  [org.apache.camel.spring.spi.BridgePropertyPlaceholderConfigurer] (MSC service thread 1-1) Loading properties file from URL [file:/opt/jboss/octopus/configuration/com.fondofbags.octopus.properties]
08:17:48,416 WARN  [org.springframework.beans.factory.support.DefaultListableBeanFactory] (MSC service thread 1-2) Bean creation exception on non-lazy FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmsConnectionFactory': Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: DefaultJMSConnectionFactory -- service jboss.naming.context.java.jboss.DefaultJMSConnectionFactory
08:17:49,170 WARN  [org.springframework.beans.factory.support.DefaultListableBeanFactory] (MSC service thread 1-1) Bean creation exception on non-lazy FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmsConnectionFactory': Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: DefaultJMSConnectionFactory -- service jboss.naming.context.java.jboss.DefaultJMSConnectionFactory
08:17:49,236 WARN  [org.springframework.context.support.GenericApplicationContext] (MSC service thread 1-2) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmsComponent' defined in URL [vfs:/content/airtable-mapper-1.0.0.war/META-INF/jboss-camel-context.xml]: Cannot resolve reference to bean 'jmsConnectionFactory' while setting bean property 'connectionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmsConnectionFactory': Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: DefaultJMSConnectionFactory -- service jboss.naming.context.java.jboss.DefaultJMSConnectionFactory
08:17:49,239 INFO  [org.apache.camel.spring.SpringCamelContext] (MSC service thread 1-2) Apache Camel 2.18.0 (CamelContext: airtableToDefaultMapper) is shutting down
08:17:49,287 INFO  [org.apache.camel.spring.SpringCamelContext] (MSC service thread 1-2) Apache Camel 2.18.0 (CamelContext: airtableToDefaultMapper) uptime
08:17:49,304 INFO  [org.apache.camel.spring.SpringCamelContext] (MSC service thread 1-2) Apache Camel 2.18.0 (CamelContext: airtableToDefaultMapper) is shutdown in 0.048 seconds
08:17:49,310 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."airtable-mapper-1.0.0.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."airtable-mapper-1.0.0.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "airtable-mapper-1.0.0.war"
Caused by: javax.naming.NameNotFoundException: DefaultJMSConnectionFactory -- service jboss.naming.context.java.jboss.DefaultJMSConnectionFactory
     at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:106)
     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:207)
     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:184)
     at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:237)
     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:193)
     at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:189)
     at javax.naming.InitialContext.lookup(InitialContext.java:417)
     at javax.naming.InitialContext.lookup(InitialContext.java:417)
     at org.springframework.jndi.JndiTemplate$1.doInContext(JndiTemplate.java:155)
     at org.springframework.jndi.JndiTemplate.execute(JndiTemplate.java:87)
     at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:152)
     at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:179)
     at org.springframework.jndi.JndiLocatorSupport.lookup(JndiLocatorSupport.java:95)
     at org.springframework.jndi.JndiObjectLocator.lookup(JndiObjectLocator.java:106)
     at org.springframework.jndi.JndiObjectFactoryBean.lookupWithFallback(JndiObjectFactoryBean.java:231)
     at org.springframework.jndi.JndiObjectFactoryBean.afterPropertiesSet(JndiObjectFactoryBean.java:217)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
     ... 28 more
08:17:49,493 INFO  [org.apache.activemq.artemis.core.server] (ServerService Thread Pool -- 66) AMQ221003: trying to deploy queue jms.queue.ExpiryQueue
08:17:49,675 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-2) WFLYJCA0007: Registered connection factory java:/JmsXA
08:17:49,805 INFO  [org.apache.activemq.artemis.core.server] (ServerService Thread Pool -- 70) AMQ221003: trying to deploy queue jms.queue.DLQ
08:17:49,813 INFO  [org.apache.activemq.artemis.core.server] (ServerService Thread Pool -- 71) AMQ221003: trying to deploy queue jms.topic.ChangedProduct
08:17:49,950 INFO  [org.apache.activemq.artemis.ra] (MSC service thread 1-2) Resource adaptor started
08:17:49,950 INFO  [org.jboss.as.connector.services.resourceadapters.ResourceAdapterActivatorService$ResourceAdapterActivator] (MSC service thread 1-2) IJ020002: Deployed: file://RaActivatoractivemq-ra
08:17:50,327 WARN  [org.springframework.context.support.GenericApplicationContext] (MSC service thread 1-1) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmsComponent' defined in URL [vfs:/content/airtable-1.0.0.war/META-INF/jboss-camel-context.xml]: Cannot resolve reference to bean 'jmsConnectionFactory' while setting bean property 'connectionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmsConnectionFactory': Invocation of init method failed; nested exception is javax.naming.NamingException: WFLYNAM0062: Failed to lookup DefaultJMSConnectionFactory [Root exception is java.lang.RuntimeException: javax.naming.NameNotFoundException: JmsXA [Root exception is java.lang.IllegalStateException]]
08:17:50,330 INFO  [org.apache.camel.spring.SpringCamelContext] (MSC service thread 1-1) Apache Camel 2.18.0 (CamelContext: airtableConnector) is shutting down
08:17:50,396 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-1) WFLYJCA0002: Bound JCA ConnectionFactory [java:/JmsXA]
08:17:50,399 INFO  [org.wildfly.extension.messaging-activemq] (MSC service thread 1-1) WFLYMSGAMQ0002: Bound messaging object to jndi name java:jboss/DefaultJMSConnectionFactory
08:17:51,156 INFO  [io.hawt.system.ConfigManager] (ServerService Thread Pool -- 71) Configuration will be discovered via JNDI
08:17:51,160 INFO  [io.hawt.jmx.JmxTreeWatcher] (ServerService Thread Pool -- 71) Welcome to hawtio 1.4.65 : http://hawt.io/ : Don't cha wish your console was hawt like me? ;-)
08:17:51,169 INFO  [io.hawt.jmx.UploadManager] (ServerService Thread Pool -- 71) Using file upload directory: /tmp/uploads
08:17:51,516 INFO  [io.undertow.servlet] (ServerService Thread Pool -- 71) jolokia-agent: Using policy access restrictor classpath:/jolokia-access.xml
08:17:53,445 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 71) WFLYUT0021: Registered web context: /hawtio
08:17:53,465 INFO  [org.wildfly.extension.camel] (ServerService Thread Pool -- 71) Add Camel endpoint: http://0.0.0.0:8080/hawtio
08:17:53,542 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 38) WFLYSRV0010: Deployed "airtable-1.0.0.war" (runtime-name : "airtable-1.0.0.war")
08:17:53,746 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://0.0.0.0:9990/management
08:17:53,750 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://0.0.0.0:9990
08:17:53,752 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) started (with errors) in 22141ms - Started 549 of 800 services (2 services failed or missing dependencies, 425 services are lazy, passive or on-demand)
```

**Comment by jamesnetherton** [comment]
Note, this would only ever be an issue on server startup where there is potentially a race between the application being started and the messaging subsystem doing the JNDI bindings.

**Comment by jamesnetherton** [comment]
Did a little more digging into this. I think an acceptable workaround for now would be to declare Spring JNDI dependencies like:

```xml
<jee:jndi-lookup id="connectionFactory" 
                 jndi-name="java:jboss/DefaultJMSConnectionFactory" 
                 lookup-on-startup="false" 
                 proxy-interface="javax.jms.ConnectionFactory"/>
```

Which avoids any eager initialisation of the bean until it's needed (I.e until some behaviour in Camel requires it).

If this problem becomes a commonly reported issue then we can revisit it.
