### ISSUE TITLE
AtomIntegrationTest fails intermittently

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1666]
https://10.8.63.16/view/wildfly-camel/job/wildfly-camel-master-windows/lastCompletedBuild/testReport/org.wildfly.camel.test.atom/AtomIntegrationTest/testConsumeAtomFeed/

```
15:38:56,388 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 31) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.wildfly.camel.test.atom.feed.AtomApplication$Proxy$_$$_WeldClientProxy
15:38:56,399 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 31) RESTEASY002200: Adding class resource org.wildfly.camel.test.atom.feed.AtomFeed from Application class org.wildfly.camel.test.atom.feed.AtomApplication$Proxy$_$$_WeldClientProxy
15:38:56,457 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 31) WFLYUT0021: Registered web context: /atom-test
15:38:56,457 INFO  [org.wildfly.extension.camel] (ServerService Thread Pool -- 31) Add Camel endpoint: http://127.0.0.1:8080/atom-test
15:38:56,479 INFO  [org.jboss.as.server] (management-handler-thread - 3) WFLYSRV0010: Deployed "atom-test.war" (runtime-name : "atom-test.war")
15:38:56,559 INFO  [org.apache.camel.impl.converter.DefaultTypeConverter] (pool-3-thread-1) Loaded 304 type converters
15:38:56,560 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) Apache Camel 2.18.2 (CamelContext: camel-3) is starting
15:38:56,560 INFO  [org.apache.camel.management.ManagedManagementStrategy] (pool-3-thread-1) JMX is enabled
15:38:56,580 INFO  [org.wildfly.extension.camel] (pool-3-thread-1) Camel context starting: camel-3
15:38:56,580 INFO  [org.wildfly.extension.camel] (MSC service thread 1-8) Bound camel naming object: java:jboss/camel/context/camel-3
15:38:56,592 INFO  [org.apache.camel.impl.DefaultRuntimeEndpointRegistry] (pool-3-thread-1) Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
15:38:56,626 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
15:38:56,634 INFO  [org.apache.camel.component.seda.SedaEndpoint] (pool-3-thread-1) Endpoint seda://end is using shared queue: seda://end with size: 2147483647
15:38:56,660 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) Route: route3 started and consuming from: atom://http://localhost:8080/atom-test/atom/feed?splitEntries=true
15:38:56,660 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) Total 1 routes, of which 1 are started.
15:38:56,660 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) Apache Camel 2.18.2 (CamelContext: camel-3) started in 0.100 seconds
15:38:59,491 WARN  [org.apache.axiom.util.stax.dialect.StAXDialectDetector] (Camel (camel-3) thread #4 - atom://http://localhost:8080/atom-test/atom/feed) Unable to determine dialect of the StAX implementation at jar:file:/E:/jenkins/workspace/wildfly-camel-master-windows/itests/standalone/basic/target/wildfly-10.1.0.Final/jboss-modules.jar!/
15:38:59,661 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) Apache Camel 2.18.2 (CamelContext: camel-3) is shutting down
15:38:59,662 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (pool-3-thread-1) Starting to graceful shutdown 1 routes (timeout 300 seconds)
15:38:59,669 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (camel-3) thread #5 - ShutdownTask) Waiting as there are still 1 inflight and pending exchanges to complete, timeout in 300 seconds. Inflights per route: [route3 = 1]
15:39:00,679 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (camel-3) thread #5 - ShutdownTask) Route: route3 shutdown complete, was consuming from: atom://http://localhost:8080/atom-test/atom/feed?splitEntries=true
15:39:00,681 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (pool-3-thread-1) Graceful shutdown of 1 routes completed in 1 seconds
15:39:00,698 INFO  [org.wildfly.extension.camel] (pool-3-thread-1) Camel context stopped: camel-3
15:39:00,702 INFO  [org.wildfly.extension.camel] (MSC service thread 1-1) Unbind camel naming object: java:jboss/camel/context/camel-3
15:39:00,711 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) Apache Camel 2.18.2 (CamelContext: camel-3) uptime 4.151 seconds
15:39:00,712 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-3-thread-1) Apache Camel 2.18.2 (CamelContext: camel-3) is shutdown in 1.050 seconds
15:39:00,726 SEVERE [org.jboss.arquillian.protocol.jmx.JMXTestRunner] (pool-3-thread-1) Failed: org.wildfly.camel.test.atom.AtomIntegrationTest.testConsumeAtomFeed: java.lang.NullPointerException
	at org.wildfly.camel.test.atom.AtomIntegrationTest.testConsumeAtomFeed(AtomIntegrationTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by tdiesler** [comment]
Won't fix (for now). Does not show at all in the [master](https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel), [stability](https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel-stability/) jobs
