### ISSUE TITLE
RequiresDocker annotated tests fail on Windows

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1725]
Seems to be trying to launch a process that may not be installed:

```
Caused by: java.io.IOException: Cannot run program "boot2docker": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.arquillian.spacelift.task.os.SpawnProcessTask.process(SpawnProcessTask.java:107)
	at org.arquillian.spacelift.task.os.SpawnProcessTask.process(SpawnProcessTask.java:34)
	at org.arquillian.spacelift.task.Task.run(Task.java:98)
	at org.arquillian.spacelift.task.Task$1.call(Task.java:70)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at org.arquillian.spacelift.task.os.SpawnProcessTask.process(SpawnProcessTask.java:107)
	at org.arquillian.spacelift.task.os.SpawnProcessTask.process(SpawnProcessTask.java:34)
	at org.arquillian.spacelift.task.Task.run(Task.java:98)
	at org.arquillian.spacelift.task.Task$1.call(Task.java:70)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by jamesnetherton** [comment]
Turns out this is somewhat worse than anticipated. Seems ARQ Cube is not very graceful when it cannot find executables which it thinks are on the `PATH`. E.g docker-machine, boot2docker etc.

I'm fixing the problems upstream but it'll need a new cube release to fix properly in WFC.
