### ISSUE TITLE
Intermittent failure of SJMSBatchIntegrationTest

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1735]
Pops up occasionally on the stability build:
 
```
java.lang.AssertionError: mock://split Received message count. Expected: <1000> but was: <80>
	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1452)
	at org.apache.camel.component.mock.MockEndpoint.assertEquals(MockEndpoint.java:1434)
	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:407)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:386)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:374)
	at org.wildfly.camel.test.sjms.SJMSBatchIntegrationTest.testBatchMessageConsumerRoute(SJMSBatchIntegrationTest.java:139)
```

**Comment by jamesnetherton** [comment]
Not seen this happen since the 2.19 upgrade so I'll close.
