### ISSUE TITLE
spring-aop cannot access org.w3c.dom.Element

### ISSUE THREAD

**Issue by klafbang** [wildfly-extras/wildfly-camel#1738]
The spring-aop module can under circumstances fail due to a missing dependency on javax.api.

I am not sure this is a full example (I am not at liberty to provide a full example), but loading this file:
[db-settings.xml](https://github.com/wildfly-extras/wildfly-camel/files/912301/db-settings.xml.txt)

Yields an exception that's roughly:
```
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/Element
      at org.springframework.aop.config.AopNamespaceUtils.useClassProxyingIfNecessary(AopNamespaceUtils.java:84)
      at org.springframework.aop.config.AopNamespaceUtils.registerAutoProxyCreatorIfNecessary(AopNamespaceUtils.java:60)

```
Adding a module dependency to spring-aop on javax.api fixes this:
```
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.1" name="org.springframework.aop">
  <properties>
    <property name="jboss.api" value="private" />
  </properties>
  <resources>
    <resource-root path="spring-aop-4.3.7.RELEASE.jar"/>
  </resources>
  <dependencies>
    **<module name="javax.api" />**
    <module name="org.apache.commons.logging" />
    <module name="org.springframework.beans" />
    <module name="org.springframework.core" />
  </dependencies>
</module>
```

**Comment by tdiesler** [comment]
Thanks for reporting this
