### ISSUE TITLE
Error while loading AWS partitions file

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1741]
When the client is built like this

```
        AmazonEC2 client = AmazonEC2ClientBuilder.standard()
                .withCredentials(new StaticCredentialsProvider(new BasicAWSCredentials(accessId, secretKey)))
                .withRegion("eu-west-1")
                .build();
```

we get 

```
com.amazonaws.AmazonClientException: Error while loading partitions file from com/amazonaws/partitions/endpoints.json
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1130)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at com.amazonaws.partitions.PartitionsLoader.loadPartitionFromStream(PartitionsLoader.java:92)
	at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:84)
	at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30)
	at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:66)
	at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:54)
	at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:107)
	at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:233)
	at org.wildfly.camel.test.aws.ec2.AWSEC2IntegrationTest.testCreateInstance(AWSEC2IntegrationTest.java:79)
```

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.amazonaws.partitions.model.Partitions]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: UNKNOWN; line: 2, column: 3]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1130)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at com.amazonaws.partitions.PartitionsLoader.loadPartitionFromStream(PartitionsLoader.java:92)
```

**Comment by tdiesler** [comment]
Blocked by camel-2.18.4

**Comment by tdiesler** [comment]
Fixed by adding

```
            <module name="com.fasterxml.jackson.core.jackson-annotations" />
```

to module com.amazon.aws
