### ISSUE TITLE
Unable to configure multiple paths for the same HTTP verb in camel REST DSL

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1789]
This should be perfectly acceptable:

```java
rest("/customers")
  .get("/").to("direct:foo")
  .get("/{id}").to("direct:bar")
```

But it results in:

```
java.lang.IllegalStateException: Handler for GET already registered
	at org.jboss.gravia.utils.IllegalStateAssertion.assertNull(IllegalStateAssertion.java:40)
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$DelegatingHttpHandler.checkedPut(CamelUndertowHostService.java:222)
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$DelegatingHttpHandler.addDelegate(CamelUndertowHostService.java:213)
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$WildFlyUndertowHost.registerHandler(CamelUndertowHostService.java:190)
	at org.apache.camel.component.undertow.UndertowConsumer.doStart(UndertowConsumer.java:73)
	at org.wildfly.extension.camel.undertow.WildFlyUndertowComponent$WildFlyUndertowUndertowConsumer.doStart(WildFlyUndertowComponent.java:90)

```

**Comment by jamesnetherton** [comment]
For a number of reasons, this turns out to be far more complex than it first seems. However, I stumbled across the (undocumented) `RoutingHandler` which enables us to configure HTTP verbs to path template strings.

One drawback on WildFly 10 is that path templates do not support wildcard expressions without REST placeholders. So it's not possible to support `isMatchOnUriPrefix == true`. This problem goes away on WildFly 11 / EAP 7.1 (due to upgraded Undertow).

Given that our current REST DSL support with `camel-undertow` is mostly broken, my plan for the community branch on WildFly 10 is to ignore `isMatchOnUriPrefix` and log a warning until master moves to WildFly 11. 

That'll at least resolve most of the major issues. If folks want really want `isMatchOnUriPrefix == true` then `camel-servlet` is always available as fallback.
