### ISSUE TITLE
DelegatingHttpHandler should return HTTP 405 when no matching handler is found

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1790]
If you configure the REST DSL like:

```
rest().get("/foo").route().setBody(constant("Hello World")).endRest();
```

And then try to hit the endpoint using an HTTP verb that is not valid:

`curl -X POST http://localhost:8080/foo`

You get:

```
08:42:00,370 ERROR [io.undertow.request] (default I/O-1) UT005071: Undertow request failed HttpServerExchange{ POST /foo request {Accept=[*/*], User-Agent=[curl/7.51.0], Host=[localhost:8080]} response {X-Powered-By=[Undertow/1], Server=[WildFly/10]}}: java.lang.IllegalStateException: Cannot obtain handler for method: POST
	at org.jboss.gravia.utils.IllegalStateAssertion.assertNotNull(IllegalStateAssertion.java:50)
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$DelegatingHttpHandler.handleRequest(CamelUndertowHostService.java:232)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at org.wildfly.extension.undertow.Host$OptionsHandler.handleRequest(Host.java:295)
```

I think it'd better to log a warning and return an HTTP 405 with the list of HTTP verbs that are allowed (which is actually what the WildFly JAX-RS subsystem does).

**Comment by jamesnetherton** [comment]
Fixed in 55b2291b2a4f410c0260cb371deaf924e9d38261.
