### ISSUE TITLE
async-http-client depends on unstable Netty APIs

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1886]
Having correctly aligned the Netty versions for #1885, it reveals a problem for the camel-ahc and camel-ahc-ws components:

```
java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContextBuilder.protocols([Ljava/lang/String;)Lio/netty/handler/ssl/SslContextBuilder;
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.buildSslContext(DefaultSslEngineFactory.java:45)
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.init(DefaultSslEngineFactory.java:69)
	at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:116)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:85)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:67)
```
 
`SslContextBuilder.protocols` is only present in specific Netty versions and neither the WildFly 4.0 Netty module or our custom 4.1.8 slot provide this.

We could possibly address this with WildFly 11, which provides Netty 4.1 by default, thus allowing us to provide our own 4.0 slot with a version suitable for async-http-client.

**Comment by tdiesler** [comment]
out of date
