### ISSUE TITLE
Enable camel-facebook integration tests

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1898]
Seems the test application has been deleted:

```
FacebookException{statusCode=400, errorType='OAuthException', errorMessage='Error validating application. Application has been deleted.', errorCode=101, errorSubcode=-1, version=2.4.8}
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1756)
	at org.apache.camel.component.facebook.FacebookProducer$1.run(FacebookProducer.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jamesnetherton** [comment]
This may be worth experimenting with:

https://github.com/snarfed/mockfacebook

Project seems pretty inactive so it'll likely need forking & updating. But we could run it in a docker container and point Camel to the mock oAuth / API endpoints.
