### ISSUE TITLE
DependencyResolutionExceptions when building the project.

### ISSUE THREAD

**Issue by Beanieman1** [wildfly-extras/wildfly-camel#1904]
Hello, I tried building the examples in this project but i keep getting a build failure. I Think this because the wildfly-camel-archetype-cdi:maven-archetype:4.8.0-SNAPSHOT dependency is not available at the repository. I'm I missing something or I'm I the only one getting the this error. Any help would be appreciated. Below is the build error.

`[ERROR] Failed to execute goal on project wildfly-camel-archetype-cdi: Could not resolve dependencies for project org.wildfly.camel.archetypes:wildfly-camel-archetype-cdi:maven-archetype:4.8.0-SNAPSHOT: Failure to find org.wildfly.camel:wildfly-camel-feature-pack:pom:4.8.0-SNAPSHOT in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository has elapsed or updates are forced -> [Help 1]`

**Comment by jamesnetherton** [comment]
IIRC the examples do not depend on the archetypes. Maybe try to build the entire project from the project root directory first (skip tests for quickness).

```
mvn clean install -Dts.all -DskipTests`
```

When the build completes you can `cd examples` and each of them should have been built.

**Comment by jamesnetherton** [comment]
Did you manage to resolve the problem?

**Comment by Beanieman1** [comment]
I have not been able to compile the whole project. The build is failing at
```
[INFO] --- maven-antrun-plugin:1.7:run (default) @ wildfly-camel-swarm ---
[INFO] Executing tasks'

```
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project wildfly-camel-swarm: An Ant BuildException has occured: Java returned: 1
[ERROR] around Ant part ...<java classname="org.wildfly.swarm.camel.generator.Main" failonerror="true" classpathref="maven.test.classpath">... @ 4:115 in C:\Users\babafemini\Desktop\Base Code\wildfly-camel-master\wildfly-camel-master\swarm\target\antrun\build-main.xml

```
Any possible solutions?

**Comment by jamesnetherton** [comment]
Please can you run the build with `-X` so that we can see a stacktrace of what's causing the error?

**Comment by jamesnetherton** [comment]
Also seeing the output from `mvn -versions` would be helpful so I can get an idea of what your environment looks like.

**Comment by Beanieman1** [comment]
This is my environment
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: C:\Program Files\apache-maven-3.5.0\bin\..
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_131\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
And here is the stacktrace of the error
```
[INFO] Reactor Summary:
[INFO]
[INFO] Wildfly Camel ...................................... SUCCESS [ 31.951 s]
[INFO] Wildfly Camel :: Config ............................ SUCCESS [01:19 min]
[INFO] WildFly Camel :: CXF Undertow ...................... SUCCESS [01:28 min]
[INFO] Wildfly Camel :: Feature ........................... SUCCESS [  7.275 s]
[INFO] Wildfly Camel :: Feature Extras .................... SUCCESS [ 54.650 s]
[INFO] Wildfly Camel :: Subsystem ......................... SUCCESS [  2.431 s]
[INFO] Wildfly Camel :: Subsystem :: Core ................. SUCCESS [ 52.228 s]
[INFO] Wildfly Camel :: Subsystem :: CDI .................. SUCCESS [ 33.853 s]
[INFO] Wildfly Camel :: Subsystem :: Security ............. SUCCESS [ 20.982 s]
[INFO] Wildfly Camel :: Subsystem :: Undertow ............. SUCCESS [ 39.650 s]
[INFO] Wildfly Camel :: Feature Pack ...................... SUCCESS [28:57 min]
[INFO] Wildfly Camel :: Catalog ........................... SUCCESS [07:10 min]
[INFO] Wildfly Camel :: Swarm ............................. FAILURE [03:01 min]
[INFO] Wildfly Camel :: Enricher .......................... SKIPPED
[INFO] Wildfly Camel :: Testsuite ......................... SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Common ............... SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Standalone ........... SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Smoke .. SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Basic .. SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Extra .. SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Docker . SKIPPED
[INFO] Wildfly Camel :: Testsuite :: Camel ................ SKIPPED
[INFO] Wildfly Camel :: Archetypes ........................ SKIPPED
[INFO] Wildfly Camel :: Archetypes :: CDI ................. SKIPPED
[INFO] Wildfly Camel :: Archetypes :: Spring .............. SKIPPED
[INFO] Wildfly Camel :: Docs .............................. SKIPPED
[INFO] Wildfly Camel :: Patch ............................. SKIPPED
[INFO] Wildfly Camel :: Example ........................... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel ActiveMQ ......... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel CDI .............. SKIPPED
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-RS ....... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel CXF JAX-WS ....... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS .............. SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS MDB .......... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS Spring ....... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS Tx ........... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JMS Tx Spring .... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JPA .............. SKIPPED
[INFO] Wildfly Camel :: Example :: Camel JPA Spring ....... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel Mail ............. SKIPPED
[INFO] Wildfly Camel :: Example :: Camel Mail Spring ...... SKIPPED
[INFO] Wildfly Camel :: Example :: Camel REST Swagger ..... SKIPPED
[INFO] Wildfly Camel :: Example :: Testsuite .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46:16 min
[INFO] Finished at: 2017-06-23T17:50:40+01:00
[INFO] Final Memory: 283M/549M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project wildfly-camel-swarm: An Ant BuildException has occured: Java returned: 1
[ERROR] around Ant part ...<java classname="org.wildfly.swarm.camel.generator.Main" failonerror="true" classpathref="maven.test.classpath">... @ 4:115 in C:\Users\babafemini\Desktop\Base Code\wildfly-camel-master\wildfly-camel-master\swarm\target\antrun\build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project wildfly-camel-swarm: An Ant BuildException has occured: Java returned: 1
around Ant part ...<java classname="org.wildfly.swarm.camel.generator.Main" failonerror="true" classpathref="maven.test.classpath">... @ 4:115 in C:\Users\babafemini\Desktop\Base Code\wildfly-camel-master\wildfly-camel-master\swarm\target\antrun\build-main.xml
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: Java returned: 1
around Ant part ...<java classname="org.wildfly.swarm.camel.generator.Main" failonerror="true" classpathref="maven.test.classpath">... @ 4:115 in C:\Users\babafemini\Desktop\Base Code\wildfly-camel-master\wildfly-camel-master\swarm\target\antrun\build-main.xml
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:355)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: C:\Users\babafemini\Desktop\Base Code\wildfly-camel-master\wildfly-camel-master\swarm\target\antrun\build-main.xml:4: Java returned: 1
        at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:327)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wildfly-camel-swarm
```

**Comment by Beanieman1** [comment]
I hope I sent what you asked for?

**Comment by jamesnetherton** [comment]
Thanks for the info. If I run with the same versions on Windows 10, it works fine for me (I'm running from the Windows Command prompt `cmd.exe`). I've also got a `JAVA_HOME` environment variable configured and the Java `bin` directory added to the `PATH`.

It's not obvious what's causing the error so I can only suggest commenting out the `swarm` module from the project `pom.xml` `modules` section to see if that helps move things along.

Maybe one other thing to try would be to bump [this version](https://github.com/wildfly-extras/wildfly-camel/blob/aa3266c35ae3fc73627bd2fbe00490163a6cf04f/pom.xml#L106) to 1.8 and see if it helps.

**Comment by Beanieman1** [comment]
Okay so I managed  to build the whole project . After which I started my server.Then i attempted to deploy the camel-cdi example. It came up with an exception just as it was about deploying.
Below was the stacktrace.

```
[DEBUG] Executing deployment
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.112 s
[INFO] Finished at: 2017-06-24T18:02:21+01:00
[INFO] Final Memory: 32M/230M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.2.0.Alpha3:deploy-only (wildfly-deploy) on project example-camel-cdi: Failed to execute goal deploy-only: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"example-camel-cdi-4.8.0-SNAPSHOT.war\"
[ERROR]     Caused by: java.lang.RuntimeException: WFLYSRV0177: Error getting reflective information for class org.wildfly.camel.examples.cdi.SimpleServlet with ClassLoader ModuleClassLoader for Module \"deployment.example-camel-cdi-4.8.0-SNAPSHOT.war:main\" from Service Module Loader
[ERROR]     Caused by: java.lang.NoClassDefFoundError: Lorg/apache/camel/CamelContext;
[ERROR]     Caused by: java.lang.ClassNotFoundException: org.apache.camel.CamelContext from [Module \"deployment.example-camel-cdi-4.8.0-SNAPSHOT.war:main\" from Service Module Loader]"},"WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE"],"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined}}}
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.2.0.Alpha3:deploy-only (wildfly-deploy) on project example-camel-cdi: Failed to execute goal deploy-only: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"example-camel-cdi-4.8.0-SNAPSHOT.war\"
    Caused by: java.lang.RuntimeException: WFLYSRV0177: Error getting reflective information for class org.wildfly.camel.examples.cdi.SimpleServlet with ClassLoader ModuleClassLoader for Module \"deployment.example-camel-cdi-4.8.0-SNAPSHOT.war:main\" from Service Module Loader
    Caused by: java.lang.NoClassDefFoundError: Lorg/apache/camel/CamelContext;
    Caused by: java.lang.ClassNotFoundException: org.apache.camel.CamelContext from [Module \"deployment.example-camel-cdi-4.8.0-SNAPSHOT.war:main\" from Service Module Loader]"},"WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE"],"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined}}}
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute goal deploy-only: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment \"example-camel-cdi-4.8.0-SNAPSHOT.war\"
    Caused by: java.lang.RuntimeException: WFLYSRV0177: Error getting reflective information for class org.wildfly.camel.examples.cdi.SimpleServlet with ClassLoader ModuleClassLoader for Module \"deployment.example-camel-cdi-4.8.0-SNAPSHOT.war:main\" from Service Module Loader
    Caused by: java.lang.NoClassDefFoundError: Lorg/apache/camel/CamelContext;
    Caused by: java.lang.ClassNotFoundException: org.apache.camel.CamelContext from [Module \"deployment.example-camel-cdi-4.8.0-SNAPSHOT.war:main\" from Service Module Loader]"},"WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.unit.\"example-camel-cdi-4.8.0-SNAPSHOT.war\".POST_MODULE"],"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined}}}
        at org.wildfly.plugin.deployment.AbstractDeployment.execute(AbstractDeployment.java:148)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Any solutions?

**Comment by jamesnetherton** [comment]
You need to have the wildfly-camel patch overlay applied to the server.

Have you read the docs? See getting started:

http://wildfly-extras.github.io/wildfly-camel/#_getting_started

Download the patch tar.gz file (or copy a local SNAPSHOT from `patch/target`). Copy it into the WildFly server root directory, extract the contents and then start the server with `bin/standalone.sh -c standalone-camel.xml`.

**Comment by Beanieman1** [comment]
I have done this already but I would redownload the wildfly 10.1.0 and wildfly-camel patch afresh. Because that can only be the possible explanation. I have been having the same exceptions before I tried using your project.

**Comment by jamesnetherton** [comment]
Installing the patch on top of the base WildFly install directory and starting the server with the appropriate config file (I.e standalone-camel.xml) should be enough to enable the Camel subsystem. If you've done things properly, you should see the following lines appear somewhere in the server startup log:

```
[org.wildfly.extension.camel] (MSC service thread 1-7) Activating Camel Subsystem
[org.wildfly.extension.camel] (MSC service thread 1-6) Bound camel naming object: java:jboss/camel/CamelContextFactory
[org.wildfly.extension.camel] (MSC service thread 1-6) Bound camel naming object: java:jboss/camel/CamelContextRegistry
```
If you don't see this, something is wrong with your installation.

**Comment by Beanieman1** [comment]
It works now.....Thanks!

**Comment by jamesnetherton** [comment]
Glad you got it working :smiley:
