### ISSUE TITLE
NameNotFoundException: infinispan/container/server

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#1933]
```
Tests in error: 
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
  InfinispanIntegrationTest.setUp:67 » NameNotFound infinispan/container/server
```

**Comment by tdiesler** [comment]
This issue occurs during setup of the [InfinispanIntegrationTest](https://github.com/wildfly-extras/wildfly-camel/blob/wildfly-11.x/itests/standalone/extra/src/test/java/org/wildfly/camel/test/infinispan/InfinispanIntegrationTest.java#L62), which happens in the context of an ARQ test deployment. If I understand correctly, deployments are now required to define a dependency on a service that makes the CacheContainer available. If so, how do we define this dependency correctly?

**Comment by pferraro** [comment]
@tdiesler Correct. Previously, cache containers and cache configurations were started passively.  This meant that non-ha cache containers would start during server startup.  However, even so, without an explicit dependency there was no guarantee that this resource would be completely started at the time that it is requested.
As of WF11 Beta1, cache containers and cache configurations start on-demand - as part of the effort to reduce startup time and memory footprint.  Consequently, these resource will not be available without the requisite dependency.
There are at least 2 ways to establish the proper dependency for JNDI resource supplied by a non-ACTIVE service:

1. Inject the resource via the EE ```@Resource``` annotation
e.g. 
```java
@Resource(lookup="java:jboss/infinispan/cache/server/default") Cache<?, ?> cache;
```
N.B. if the ```@Resource``` is used within the a CDI managed bean, the dependency isn't established correctly due to a known bug.

2. Use a ```<resource-ref/>``` or ```<resource-env-ref/>``` in your deployment descriptor, then reference the resource via its component/module/app namespace.
e.g.
```xml
<resource-env-ref>
    <resource-env-ref-name>cache/foo</resource-env-ref-name>
    <resource-env-ref-type>org.infinispan.Cache</resource-env-ref-type>
    <lookup-name>java:jboss/infinispan/cache/server/default</lookup-name>
</resource-env-ref>
```
```java
Cache<?, ?> cache = (Cache<?, ?>) new InitialContext().lookup("java:comp/env/cache/foo");
```
or
```java
@Resource(name="cache/foo") Cache<?, ?> cache;
```

**Comment by tdiesler** [comment]
When I inject the container like this in [InfinispanIntegrationTest](https://github.com/tdiesler/wildfly-camel/blob/wfc1933/itests/standalone/extra/src/test/java/org/wildfly/camel/test/infinispan/InfinispanIntegrationTest.java#L59)

```
    @Resource(lookup="java:jboss/infinispan/cache/server/default")
    public Cache<Object, Object> cache;
```

I get 

```
Caused by: java.lang.IllegalArgumentException: WFLYWELD0049: Error injecting resource into CDI managed bean. Can't find a resource named java:jboss/infinispan/cache/server/default defined on public org.infinispan.Cache org.wildfly.camel.test.infinispan.InfinispanIntegrationTest.cache
	at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices.resolveResource(WeldResourceInjectionServices.java:225)
	at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices$1.createResource(WeldResourceInjectionServices.java:169)
	at org.jboss.weld.injection.AbstractResourceInjection.getResourceReference(AbstractResourceInjection.java:49)
	at org.jboss.weld.injection.AbstractResourceInjection.injectResourceReference(AbstractResourceInjection.java:63)
	at org.jboss.weld.util.Beans.injectEEFields(Beans.java:331)
	at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
	at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
	at org.jboss.arquillian.testenricher.cdi.CDIInjectionEnricher.injectNonContextualInstance(CDIInjectionEnricher.java:145)
	at org.jboss.arquillian.testenricher.cdi.CDIInjectionEnricher.injectClass(CDIInjectionEnricher.java:125)
	... 127 more
Caused by: javax.naming.NameNotFoundException: infinispan/cache/server/default [Root exception is java.lang.IllegalStateException]
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:153)
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:83)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:207)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:184)
	at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:239)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:193)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:189)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices.resolveResource(WeldResourceInjectionServices.java:223)
	... 137 more
```

**Comment by paulsvm** [comment]
I am also facing same problem in wildfly 11. In which version can i find the solution.

**Comment by pferraro** [comment]
@paulsvm Please direct your questions to the WildFly forums: https://developer.jboss.org/en/wildfly
