### ISSUE TITLE
camel-lucene component is not compatible with the WildFly Lucene module

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#194]
When the component is loaded against the WildFly Lucene module, it results in:
```
java.lang.NoSuchFieldError: LUCENE_46
	at org.apache.camel.component.lucene.LuceneConfiguration.<init>(LuceneConfiguration.java:38)
	at org.apache.camel.component.lucene.LuceneComponent.<init>(LuceneComponent.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
```
Not surprising as WildFly Lucene 3.6.2 has no handle on org.apache.lucene.util.Version.LUCENE_46.

The problem code is [here](https://github.com/apache/camel/blob/master/components/camel-lucene/src/main/java/org/apache/camel/component/lucene/LuceneConfiguration.java#L38). 

Maybe the version can be made to be configurable, but then there's no guarantee that any of the other component code will work properly. 3.6.2 to 4.6 is quite a large jump.

**Comment by tdiesler** [comment]
wildfly-9.0.0.Alpha1 runs on lucene-3.6.2

```
[tdiesler@macbook standalone]$ find target/wildfly-9.0.0.Alpha1/modules -name "*.jar" | grep lucene
target/wildfly-9.0.0.Alpha1/modules/org/apache/camel/component/lucene/main/camel-lucene-2.14.1.jar
target/wildfly-9.0.0.Alpha1/modules/system/layers/base/org/apache/lucene/main/lucene-analyzers-3.6.2.jar
target/wildfly-9.0.0.Alpha1/modules/system/layers/base/org/apache/lucene/main/lucene-core-3.6.2.jar
target/wildfly-9.0.0.Alpha1/modules/system/layers/base/org/apache/lucene/main/lucene-facet-3.6.2.jar
target/wildfly-9.0.0.Alpha1/modules/system/layers/base/org/apache/lucene/main/lucene-memory-3.6.2.jar
target/wildfly-9.0.0.Alpha1/modules/system/layers/base/org/hibernate/hql/main/hibernate-hql-lucene-1.0.0.Alpha6.jar
target/wildfly-9.0.0.Alpha1/modules/system/layers/base/org/infinispan/lucene/directory/main/infinispan-lucene-directory-6.0.2.Final.jar
target/wildfly-9.0.0.Alpha1/modules/system/layers/base/org/infinispan/lucene/main/infinispan-lucene-v3-6.0.2.Final.jar
```

**Comment by tdiesler** [comment]
On wildfly-9.0.0.Alpha2-SNAPSHOT with lucene-4.8.1 

```
[tdiesler@macbook standalone]$ find target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules -name "*.jar" | grep lucene
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/org/apache/camel/component/lucene/main/camel-lucene-2.14.1.jar
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/apache/lucene/main/lucene-analyzers-common-4.8.1.jar
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/apache/lucene/main/lucene-core-4.8.1.jar
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/apache/lucene/main/lucene-facet-4.8.1.jar
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/apache/lucene/main/lucene-memory-4.8.1.jar
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/apache/lucene/main/lucene-queries-4.8.1.jar
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/hibernate/hql/main/hibernate-hql-lucene-1.1.0.Alpha3.jar
target/wildfly-9.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/infinispan/lucene/directory/main/infinispan-lucene-directory-7.0.0.CR2.jar
```

I also get

```
15:53:21,328 ERROR [io.fabric8.insight.elasticsearch-factory:2.0.0.SNAPSHOT] (MSC service thread 1-2) [io.fabric8.elasticsearch] The activate method has thrown an exception: java.lang.NoSuchFieldError: LUCENE_3_6
	at org.elasticsearch.Version.<clinit>(Version.java:45) [elasticsearch-1.4.2.jar:]
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:136) [elasticsearch-1.4.2.jar:]
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159) [elasticsearch-1.4.2.jar:]
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166) [elasticsearch-1.4.2.jar:]
	at io.fabric8.insight.elasticsearch.impl.ElasticsearchNode.activate(ElasticsearchNode.java:54) [insight-elasticsearch-factory-2.0-SNAPSHOT.jar:]
```

**Comment by tdiesler** [comment]
We provide alternative lucene modules until we can use the wildfly ones
