### ISSUE TITLE
cannot run wildfly by launch.sh

### ISSUE THREAD

**Issue by michael2043** [wildfly-extras/wildfly-camel#1946]
I following every step by this video
https://www.youtube.com/watch?v=7ErZpiPglqg
but when I run ./launch.sh in command line ,error happened

[root@localhost bin]# ./launch.sh
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/wildfly

  JAVA: /home/jdk/jdk1.8.0_40/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

23:52:23,964 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.2.Final
java.lang.IllegalStateException: WFLYCTL0214: Could not get main file: -b. Specified files must be relative to the configuration dir: /opt/wildfly/standalone/configuration
        at org.jboss.as.controller.persistence.ConfigurationFile.determineMainFile(ConfigurationFile.java:312)
        at org.jboss.as.controller.persistence.ConfigurationFile.<init>(ConfigurationFile.java:173)
        at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:456)
        at org.jboss.as.server.Main.determineEnvironment(Main.java:297)
        at org.jboss.as.server.Main.main(Main.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.jboss.modules.Module.run(Module.java:330)
        at org.jboss.modules.Main.main(Main.java:505)
23:52:24,195 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1

**Comment by jamesnetherton** [comment]
You may want to ask the WildFly project team:

https://github.com/wildfly/wildfly

But if you look at the script, you can see it's expecting 3 parameters passed to it:

![wf-launch](https://user-images.githubusercontent.com/4721408/29035596-125240b2-7b94-11e7-8bcd-7c0c2209ce64.png)

So something like this should probably work:

`./launch.sh standalone standalone.xml 0.0.0.0`

However, I don't think it's designed to be executed manually, it's supposed to be executed by an init daemon (Systemd etc).

I'll close this, if you need more help, try the WildFly team.
