### ISSUE TITLE
InfluxDBIntegrationTest fails with Camel 2.20.x

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1952]
```
Caused by: java.lang.ClassNotFoundException: com.squareup.moshi.Moshi$Builder from [Module "org.apache.camel.component.influxdb:main" from local module loader @1ee807c6 (finder: local module finder @76a4d6c (roots: /home/james/Projects/git/master/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules,/home/james/Projects/git/master/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules/system/layers/fuse,/home/james/Projects/git/master/wildfly-camel/itests/standalone/docker/target/wildfly-10.1.0.Final/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	... 131 more
```

**Comment by jamesnetherton** [comment]
Done.
