### ISSUE TITLE
SalesforceIntegrationTest fails with Camel 2.20.x

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#1953]
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/jsonSchema/types/SimpleTypeSchema
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.apache.camel.component.salesforce.internal.SalesforceSession.<init>(SalesforceSession.java:104)
	at org.apache.camel.component.salesforce.SalesforceComponent.doStart(SalesforceComponent.java:365)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3683)
	at org.apache.camel.impl.DefaultCamelContext.startServices(DefaultCamelContext.java:3689)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3420)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:207)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3231)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3227)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3250)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3227)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3150)
	at org.wildfly.camel.test.salesforce.SalesforceIntegrationTest.testSalesforceQuery(SalesforceIntegrationTest.java:88)
```

**Comment by jamesnetherton** [comment]
Done.
