### ISSUE TITLE
SalesforceIntegrationTest fails with Camel 2.19.3

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2073]
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/jsonSchema/types/SimpleTypeSchema
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at org.apache.camel.component.salesforce.internal.SalesforceSession.<init>(SalesforceSession.java:103)
	at org.apache.camel.component.salesforce.SalesforceComponent.doStart(SalesforceComponent.java:357)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3514)
	at org.apache.camel.impl.DefaultCamelContext.startServices(DefaultCamelContext.java:3520)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3268)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:202)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3089)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3085)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3108)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3085)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3022)
	at org.wildfly.camel.test.salesforce.SalesforceIntegrationTest.testSalesforceQuery(SalesforceIntegrationTest.java:88)
```

**Comment by jamesnetherton** [comment]
https://ci.fabric8.io/view/wildfly-camel/job/wildfly-camel/1155
