### ISSUE TITLE
NPE in Kinesis waiters API

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2096]
```
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wildfly.camel.test.common.aws.KinesisUtils.createStream(KinesisUtils.java:57)
	at org.wildfly.camel.test.aws.subA.KinesisClientProducer.getClientProvider(KinesisClientProducer.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	... 144 more
Caused by: java.lang.NullPointerException
	at com.amazonaws.waiters.WaiterImpl$1.call(WaiterImpl.java:113)
	at com.amazonaws.waiters.WaiterImpl$1.call(WaiterImpl.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by tdiesler** [comment]
Need to give waiter callback
