### ISSUE TITLE
Failed to define class HBaseZeroCopyByteString

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2127]
```
mvn clean install -Dtest=HBaseIntegrationTest
```

```
11:14:10,720 WARN  [org.jboss.modules] (hconnection-0x666cd0ed-metaLookup-shared--pool1-t1) Failed to define class com.google.protobuf.HBaseZeroCopyByteString in Module "org.apache.hbase:main" from local module loader @32cf48b7 (finder: local module finder @679b62af (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/extra/target/wildfly-10.1.0.Final/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/extra/target/wildfly-10.1.0.Final/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/extra/target/wildfly-10.1.0.Final/modules/system/layers/base)): java.lang.IllegalAccessError: Failed to link com/google/protobuf/HBaseZeroCopyByteString (Module "org.apache.hbase:main" from local module loader @32cf48b7 (finder: local module finder @679b62af (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/extra/target/wildfly-10.1.0.Final/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/extra/target/wildfly-10.1.0.Final/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/extra/target/wildfly-10.1.0.Final/modules/system/layers/base))): class com.google.protobuf.HBaseZeroCopyByteString cannot access its superclass com.google.protobuf.LiteralByteString
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:446)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
	at org.jboss.modules.Module.loadModuleClass(Module.java:606)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at org.apache.hadoop.hbase.util.ByteStringer.<clinit>(ByteStringer.java:44)
	at org.apache.hadoop.hbase.protobuf.RequestConverter.buildRegionSpecifier(RequestConverter.java:1037)
	at org.apache.hadoop.hbase.protobuf.RequestConverter.buildScanRequest(RequestConverter.java:488)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:194)
	at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallable.call(ClientSmallScanner.java:180)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:360)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:334)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

caused by 

```
com.google.protobuf.HBaseZeroCopyByteString cannot access its superclass 
com.google.protobuf.LiteralByteString
```

**Comment by tdiesler** [comment]
com.google.protobuf.HBaseZeroCopyByteString come from hbase-protocol-1.2.1.jar
com.google.protobuf.LiteralByteString comes from protobuf-java-2.5.0.jar

This seem to be a split package issue

**Comment by tdiesler** [comment]
Here is a hack

```
[tdiesler@macbook extra]$ jar tf ~/.m2/repository/org/apache/hbase/hbase-protocol/1.2.1/hbase-protocol-1.2.1.jar | grep google
com/google/
com/google/protobuf/
com/google/protobuf/HBaseZeroCopyByteString.class
```
