### ISSUE TITLE
Add support for custom ports on Undertow endpoint configuration 

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2129]
```
java.lang.IllegalStateException: Cannot register duplicate handler for GET: /
	at org.jboss.gravia.utils.IllegalStateAssertion.assertFalse(IllegalStateAssertion.java:69)
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$DelegatingRoutingHandler.add(CamelUndertowHostService.java:283)
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$WildFlyUndertowHost.registerHandler(CamelUndertowHostService.java:217)
	at org.apache.camel.component.undertow.UndertowComponent.registerConsumer(UndertowComponent.java:296)
	at org.apache.camel.component.undertow.UndertowConsumer.doStart(UndertowConsumer.java:59)
	at org.wildfly.extension.camel.undertow.WildFlyUndertowComponent$WildFlyUndertowUndertowConsumer.doStart(WildFlyUndertowComponent.java:92)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3514)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRouteConsumers(DefaultCamelContext.java:3831)
	at org.apache.camel.impl.DefaultCamelContext.doStartRouteConsumers(DefaultCamelContext.java:3767)
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3687)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3451)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3305)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:202)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3089)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3085)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3108)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3085)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3022)
	at org.wildfly.camel.test.ribbon.RibbonIntegrationTest.testServiceCall(RibbonIntegrationTest.java:90)
```

An itest to reproduce:

```

package org.wildfly.camel.test.ribbon;

import org.apache.camel.CamelContext;
import org.apache.camel.ProducerTemplate;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.component.mock.MockEndpoint;
import org.apache.camel.component.ribbon.RibbonConfiguration;
import org.apache.camel.component.ribbon.cloud.RibbonServiceLoadBalancer;
import org.apache.camel.impl.DefaultCamelContext;
import org.apache.camel.impl.cloud.StaticServiceDiscovery;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.wildfly.extension.camel.CamelAware;

/**
 * @author <a href="https://github.com/ppalaga">Peter Palaga</a>
 */
@CamelAware
@RunWith(Arquillian.class)
public class RibbonIntegrationTest {

    @Deployment
    public static JavaArchive createDeployment() {
        return ShrinkWrap.create(JavaArchive.class, "camel-ribbon-tests.jar");
    }

    @Test
    public void testServiceCall() throws Exception {
        CamelContext camelctx = new DefaultCamelContext();
        camelctx.addRoutes(new RouteBuilder() {
            @Override
            public void configure() throws Exception {
                StaticServiceDiscovery servers = new StaticServiceDiscovery();
                servers.addServer("my-service", "localhost", 8080);
                servers.addServer("my-service", "localhost", 8081);

                RibbonConfiguration configuration = new RibbonConfiguration();
                RibbonServiceLoadBalancer loadBalancer = new RibbonServiceLoadBalancer(configuration);

                from("direct:start") //
                        .serviceCall() //
                        .name("my-service") //
                        .uri("undertow:http://my-service/my-app").loadBalancer(loadBalancer) //
                        .serviceDiscovery(servers) //
                        .end() //
                        .to("mock:result");

                from("undertow:http://localhost:8080/my-app") //
                        .to("mock:8080") //
                        .transform().constant("8080");
                from("undertow:http://localhost:8081/my-app") //
                        .to("mock:8081") //
                        .transform().constant("8081");
            }
        });

        MockEndpoint mockEndpoint8080 = camelctx.getEndpoint("mock:8080", MockEndpoint.class);
        mockEndpoint8080.expectedMessageCount(1);
        MockEndpoint mockEndpoint8081 = camelctx.getEndpoint("mock:8081", MockEndpoint.class);
        mockEndpoint8081.expectedMessageCount(1);
        MockEndpoint mockEndpointResult = camelctx.getEndpoint("mock:result", MockEndpoint.class);
        mockEndpointResult.expectedMessageCount(2);

        try {
            camelctx.start();
            ProducerTemplate template = camelctx.createProducerTemplate();

            Thread.sleep(20000);
            String out = template.requestBody("direct:start", null, String.class);
            String out2 = template.requestBody("direct:start", null, String.class);
            Assert.assertEquals("8081", out);
            Assert.assertEquals("8080", out2);

            mockEndpoint8080.assertIsSatisfied();
            mockEndpoint8081.assertIsSatisfied();
            mockEndpointResult.assertIsSatisfied();
        } finally {
            camelctx.stop();
        }
    }

}
```

**Comment by jamesnetherton** [comment]
I think this is more of a feature request rather than a bug. 

At the moment our camel-undertow integration ignores the port configuration because we use the default host set in the WildFly configuration. Therefore, I'm not sure camel-ribbon can really work properly with things in their current state.

We could maybe look into whether additional undertow servers can be registered at runtime (IIRC they cannot be without a server restart).

**Comment by ppalaga** [comment]
> At the moment our camel-undertow integration ignores the port configuration because we use the default host set in the WildFly configuration. 

Good to know, thanks.

> I think this is more of a feature request rather than a bug.

Feel free to re-classify.

> Therefore, I'm not sure camel-ribbon can really work properly with things in their current state.

No, I do not think this harms camel-ribbon in a substantial way. It only blocks the simplest way to test ribbon. Our Ribbon port in itself works as expected. 

> We could maybe look into whether additional undertow servers can be registered at runtime (IIRC they cannot be without a server restart).

As I said, this is no blocker for Ribbon. I took a different strategy to test it. 

I am not sure myself how important the present issue is.

**Comment by jamesnetherton** [comment]
Wont fix for now. Running everything on the default host is fine for the majority of use cases. If folks need to use other ports, then they'll need to register their own listeners / sockets in the WildFly config. This is pretty much in line with how HTTP works on Karaf too.

If we get user requests to add this feature, we can always reopen this.

**Comment by vitorvr** [comment]
@jamesnetherton Do you have an idea how to create the listeners/sockets in the Wildfly? I need to create 2 endpoints into different ports instead of 8080. Thanks!

**Comment by ppalaga** [comment]
@vitorvr the general answer for WildFly is http://docs.wildfly.org/13/Admin_Guide.html#socket-binding-groups Please note that we currently do not support multiple ports for Undertow Camel endpoints on WildFly Camel.
