### ISSUE TITLE
NoSuchMethodError: CMSSignedDataParser.getDigestAlgorithmIDs()Ljava/util/Set

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2215]
Because the stability build runs with log level DEBUG, it picked up an incompatibility with Bouncycastle and the crypto-cms component:

```
Caused by: java.lang.NoSuchMethodError: org.bouncycastle.cms.CMSSignedDataParser.getDigestAlgorithmIDs()Ljava/util/Set;
	at org.apache.camel.component.crypto.cms.sig.SignedDataVerifier.debugLog(SignedDataVerifier.java:129)
	at org.apache.camel.component.crypto.cms.sig.SignedDataVerifier.unmarshalInternal(SignedDataVerifier.java:78)
	at org.apache.camel.component.crypto.cms.common.CryptoCmsUnmarshaller.process(CryptoCmsUnmarshaller.java:62)
	at org.apache.camel.component.crypto.cms.sig.SignedDataVerifierFromHeader.process(SignedDataVerifierFromHeader.java:58)
	at org.apache.camel.component.crypto.cms.CryptoCmsProducer.process(CryptoCmsProducer.java:41)
```

**Comment by jamesnetherton** [comment]
This will work fine on WF 11.x & EAP 7.x as this method is present in the Bouncycastle version that they ship (1.56.x). WF 10 lags some way behind on 1.52.

**Comment by jamesnetherton** [comment]
The upgrade to WF 11 fixes this.
