### ISSUE TITLE
Intermittent failure of SipIntegrationTest

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2229]
This pops up in the CI environment occassionally:

```
java.lang.AssertionError: mock://notification Received message count 0, expected at least 1
	at org.wildfly.camel.test.sip.SipIntegrationTest.testPresenceAgentBasedPubSub(SipIntegrationTest.java:79)
```

There are some exceptions in the test log:

```
&amp#27;[0m&amp#27;[31m10:36:04,409 ERROR [PresenceAgent] (PipelineThread-0) Detected a parse error: java.text.ParseException: [C@5cf84b8b
Unexpected Token : Call-ID
	at gov.nist.core.LexerCore.match(LexerCore.java:231)
	at gov.nist.javax.sip.parser.CallIDParser.parse(CallIDParser.java:66)
	at gov.nist.javax.sip.parser.StringMsgParser.processHeader(StringMsgParser.java:280)
	at gov.nist.javax.sip.parser.StringMsgParser.parseSIPMessage(StringMsgParser.java:170)
	at gov.nist.javax.sip.parser.PipelinedMsgParser.run(PipelinedMsgParser.java:304)
	at java.lang.Thread.run(Thread.java:745)

&amp#27;[0m&amp#27;[31m10:36:04,415 ERROR [org.apache.camel.component.sip.listener.SipPresenceAgentListener] (EventScannerThread) Exception thrown during publish/notify processing in the Sip Presence Agent Listener: java.lang.NullPointerException
	at org.apache.camel.component.sip.listener.SipPresenceAgentListener.sendNotification(SipPresenceAgentListener.java:82)
	at org.apache.camel.component.sip.listener.SipPresenceAgentListener.processPublish(SipPresenceAgentListener.java:124)
	at org.apache.camel.component.sip.listener.SipPresenceAgentListener.processRequest(SipPresenceAgentListener.java:64)
	at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:227)
	at gov.nist.javax.sip.EventScanner.run(EventScanner.java:517)
	at java.lang.Thread.run(Thread.java:745)

&amp#27;[0m&amp#27;[0m10:36:14,380 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-2-thread-1) Apache Camel 2.20.0 (CamelContext: camel-255) is shutting down
&amp#27;[0m&amp#27;[0m10:36:14,381 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (pool-2-thread-1) Starting to graceful shutdown 2 routes (timeout 300 seconds)
&amp#27;[0m&amp#27;[0m10:36:14,381 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (camel-255) thread #429 - ShutdownTask) Route: route325 shutdown complete, was consuming from: sip://johndoe@localhost:17190?eventHeaderName=evtHdrName&eventId=evtid&stackName=Subscriber&toHost=localhost&toPort=17189&toUser=agent
&amp#27;[0m&amp#27;[31m10:36:14,385 ERROR [PresenceAgent] (PipelineThread-0) Detected a parse error: java.text.ParseException: [C@794d5e00 getNextChar: End of buffer
	at gov.nist.core.StringTokenizer.getNextChar(StringTokenizer.java:147)
	at gov.nist.core.LexerCore.peekNextToken(LexerCore.java:187)
	at gov.nist.javax.sip.parser.URLParser.uriReference(URLParser.java:339)
	at gov.nist.javax.sip.parser.RequestLineParser.parse(RequestLineParser.java:60)
	at gov.nist.javax.sip.parser.StringMsgParser.processFirstLine(StringMsgParser.java:230)
	at gov.nist.javax.sip.parser.StringMsgParser.parseSIPMessage(StringMsgParser.java:158)
	at gov.nist.javax.sip.parser.PipelinedMsgParser.run(PipelinedMsgParser.java:304)
	at java.lang.Thread.run(Thread.java:745)
```

CrossRefs:
https://issues.apache.org/jira/browse/CAMEL-12048
https://issues.redhat.com/browse/ENTESB-13952

**Comment by tdiesler** [comment]
This seems to be out of date or not captured by this jenkins job
https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel-wfc2229/

**Comment by tdiesler** [comment]
Still shows, also on the product branch.
CrossRef: https://issues.redhat.com/browse/ENTESB-13952
