### ISSUE TITLE
ChronicleEngineIntegrationTest fails on IBM JDK

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2240]
Seems there is no `java.lang.AbstractStringBuilder` on IBM JDK. Chronicle libraries [reference it](https://github.com/search?q=org%3AOpenHFT+abstractstringbuilder&type=Code) in a few places.

```
java.lang.AbstractStringBuilder
	at net.openhft.chronicle.core.util.StringUtils.<clinit>(StringUtils.java:50)
	at net.openhft.chronicle.core.pool.StringBuilderPool.acquireStringBuilder(StringBuilderPool.java:32)
	at net.openhft.chronicle.wire.Wires.acquireStringBuilder(Wires.java:149)
	at net.openhft.chronicle.engine.map.remote.RemoteKVSSubscription.toUri(RemoteKVSSubscription.java:65)
	at net.openhft.chronicle.engine.map.remote.RemoteKVSSubscription.<init>(RemoteKVSSubscription.java:57)
	at net.openhft.chronicle.engine.tree.VanillaAsset$$Lambda$1385.0000000025193610.create(Unknown Source)
	at net.openhft.chronicle.engine.tree.VanillaAsset.createLeafView(VanillaAsset.java:350)
	at net.openhft.chronicle.engine.tree.VanillaAsset.createLeafView(VanillaAsset.java:353)
	at net.openhft.chronicle.engine.tree.VanillaAsset.createLeafView(VanillaAsset.java:353)
	at net.openhft.chronicle.engine.tree.VanillaAsset.lambda$acquireView$8(VanillaAsset.java:413)
	at net.openhft.chronicle.engine.tree.VanillaAsset$$Lambda$1395.0000000026B90ED0.call(Unknown Source)
	at net.openhft.chronicle.threads.Threads.withThreadGroup(Threads.java:42)
	at net.openhft.chronicle.engine.tree.VanillaAsset.acquireView(VanillaAsset.java:412)
	at net.openhft.chronicle.engine.api.tree.AssetTree.acquireSubscription(AssetTree.java:283)
	at net.openhft.chronicle.engine.api.tree.AssetTree.registerSubscriber(AssetTree.java:208)
	at org.apache.camel.component.chronicle.engine.ChronicleEngineConsumer.doStart(ChronicleEngineConsumer.java:58)
```

**Comment by jamesnetherton** [comment]
I raised an issue to query support for IBM JDK:

https://github.com/OpenHFT/Chronicle-Core/issues/44
