### ISSUE TITLE
APNS server uses hard coded ports

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2292]
I've seen this repeatedly with wildfly-12.x and eap-7.1.0.GA-redhat-11

```
11:31:19,396 ERROR [stderr] (Thread-226) Caused by: java.net.BindException: Address already in use (Bind failed)
11:31:19,396 ERROR [stderr] (Thread-226) 	at java.net.PlainSocketImpl.socketBind(Native Method)
11:31:19,396 ERROR [stderr] (Thread-226) 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
11:31:19,396 ERROR [stderr] (Thread-226) 	at java.net.ServerSocket.bind(ServerSocket.java:375)
11:31:19,396 ERROR [stderr] (Thread-226) 	at java.net.ServerSocket.<init>(ServerSocket.java:237)
11:31:19,396 ERROR [stderr] (Thread-226) 	at java.net.ServerSocket.<init>(ServerSocket.java:181)
11:31:19,396 ERROR [stderr] (Thread-226) 	at javax.net.ssl.SSLServerSocket.<init>(SSLServerSocket.java:136)
11:31:19,396 ERROR [stderr] (Thread-226) 	at sun.security.ssl.SSLServerSocketImpl.<init>(SSLServerSocketImpl.java:113)
11:31:19,396 ERROR [stderr] (Thread-226) 	at sun.security.ssl.SSLServerSocketFactoryImpl.createServerSocket(SSLServerSocketFactoryImpl.java:79)
11:31:19,396 ERROR [stderr] (Thread-226) 	at com.notnoop.apns.utils.ApnsServerStub$GatewayRunner.run(ApnsServerStub.java:158)
```

The testsuite hangs for minutes and then continues. Perhaps a timeout on the mock endpoint is also needed

```
[INFO] Wildfly Camel :: Testsuite :: Standalone :: Basic .. FAILURE [17:38 min]
```

**Comment by tdiesler** [comment]
If the server needs to start on the client side, we have a utility that can transport port numbers in a deployment resource.
