### ISSUE TITLE
Enable ServiceNowIntegrationTest in Jenkins

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2331]
Master build seems to have been broken for some time:

```
&amp#27;[0m&amp#27;[0m11:36:30,346 INFO  [org.apache.camel.component.servicenow.ServiceNowEndpoint] (pool-2-thread-1) Producer for ServiceNow Rel. FUJI = FUJI/org.apache.camel.component.servicenow.releases.fuji.FujiServiceNowProducer
&amp#27;[0m&amp#27;[0m11:36:30,352 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-2-thread-1) Route: route44 started and consuming from: direct://start
&amp#27;[0m&amp#27;[0m11:36:30,352 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-2-thread-1) Total 1 routes, of which 1 are started
&amp#27;[0m&amp#27;[0m11:36:30,352 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-2-thread-1) Apache Camel 2.20.1 (CamelContext: camel-37) started in 0.454 seconds
&amp#27;[0m&amp#27;[33m11:36:30,695 WARNING [org.apache.cxf.phase.PhaseInterceptorChain] (pool-2-thread-1) Interceptor for {https://ven01685.service-now.com/api}WebClient has thrown exception, unwinding now: javax.ws.rs.client.ResponseProcessingException: java.io.IOException: JSON Sequence is broken
	at org.apache.cxf.rs.security.oauth2.client.OAuthClientUtils.getAccessToken(OAuthClientUtils.java:314)
	at org.apache.cxf.rs.security.oauth2.client.OAuthClientUtils.getAccessToken(OAuthClientUtils.java:231)
	at org.apache.cxf.rs.security.oauth2.client.OAuthClientUtils.getAccessToken(OAuthClientUtils.java:179)
	at org.apache.camel.component.servicenow.auth.OAuthToken.getOrRefreshAccessToken(OAuthToken.java:49)
	at org.apache.camel.component.servicenow.auth.OAuthToken.getAuthString(OAuthToken.java:104)
	at org.apache.camel.component.servicenow.auth.AuthenticationRequestFilter.filter(AuthenticationRequestFilter.java:46)
	at org.apache.cxf.jaxrs.client.spec.ClientRequestFilterInterceptor.handleMessage(ClientRequestFilterInterceptor.java:60)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:677)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1040)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:862)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:330)
	at org.apache.camel.component.servicenow.ServiceNowClient.invoke(ServiceNowClient.java:175)
	at org.apache.camel.component.servicenow.ServiceNowClient.invoke(ServiceNowClient.java:147)
	at org.apache.camel.component.servicenow.releases.fuji.FujiServiceNowTableProcessor.retrieveRecord(FujiServiceNowTableProcessor.java:76)
	at org.apache.camel.component.servicenow.releases.fuji.FujiServiceNowTableProcessor.doProcess(FujiServiceNowTableProcessor.java:40)
	at org.apache.camel.component.servicenow.releases.fuji.FujiServiceNowProcessor.process(FujiServiceNowProcessor.java:42)
	at org.apache.camel.impl.BaseSelectorProducer.process(BaseSelectorProducer.java:35)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:541)
	at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:506)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:264)
	at org.apache.camel.impl.DefaultProducerTemplate.requestBodyAndHeaders(DefaultProducerTemplate.java:355)
	at org.wildfly.camel.test.servicenow.ServiceNowIntegrationTest.testSearchIncidents(ServiceNowIntegrationTest.java:100)
```

**Comment by jamesnetherton** [comment]
Seems to be an issue with the developer account we're using, so disabled the test for now.

**Comment by jamesnetherton** [comment]
Done.
