### ISSUE TITLE
JCache component cannot use CaffeineCachingProvider

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2423]
```
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider from [Module "deployment.camel-jcache-tests" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at javax.cache.Caching$CachingProviderRegistry.loadCachingProvider(Caching.java:485)
	... 166 more
```

**Comment by jamesnetherton** [comment]
The caffeine jcache extension isn't part of the distro so there's no work to do here.
