### ISSUE TITLE
Camel CXF component does not work with AsyncResponse

### ISSUE THREAD

**Issue by anbeng** [wildfly-extras/wildfly-camel#2447]
When creating a rsServer that uses an asyncResponse, a null pointer exception is thrown

Creating the service:
```
<cxf:rsServer id="cxfTestService"
              address="http://localhost:8080/api/"
              serviceClass="TestService">
    	<cxf:providers>
    	    <ref bean="jacksonProvider"/>
    	</cxf:providers>              
</cxf:rsServer>
```

TestService definition:
```	
@POST
@Path("/validate")
public void validate{@Suspended final AsyncResponse asyncResponse) {
}
```

Exception when calling the endpoint:
```
2018-03-20 13:36:48,818 ERROR [io.undertow.request] (default task-52) UT005023: Exception handling request to /api/validate: java.lang.NullPointerException
	at org.apache.cxf.jaxrs.impl.AsyncResponseImpl.initContinuation(AsyncResponseImpl.java:306)
	at org.apache.cxf.jaxrs.impl.AsyncResponseImpl.<init>(AsyncResponseImpl.java:68)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameter(JAXRSUtils.java:819)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:793)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:212)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:77)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:263)
	at org.apache.cxf.transport.undertow.UndertowHTTPDestination.doService(UndertowHTTPDestination.java:187)
	at org.apache.cxf.transport.undertow.UndertowHTTPDestination.doService(UndertowHTTPDestination.java:173)
	at org.apache.cxf.transport.undertow.wildfly.WildflyHTTPServerEngine$DefaultServlet.service(WildflyHTTPServerEngine.java:119)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
The call is failing on the method below. Not sure how ContinuationProvider is specified, but is null.

```
private void initContinuation() {
        ContinuationProvider provider = (ContinuationProvider)inMessage.get(ContinuationProvider.class.getName());
        cont = provider.getContinuation();
        initialSuspend = true;
}
```

This may be a usage issue, apologies if it is.

**Comment by jamesnetherton** [comment]
Which WildFly-Camel version was this tested on?

**Comment by anbeng** [comment]
Testing on wildfly 11 and wildfly-camel 5.1.0

**Comment by jamesnetherton** [comment]
Thanks for confirming - I'll take a look into it.

**Comment by jamesnetherton** [comment]
The problem is [here](https://github.com/wildfly-extras/wildfly-camel/blob/master/cxfhttp/src/main/java/org/apache/cxf/transport/undertow/wildfly/WildflyHTTPServerEngine.java#L60). To support async we'd need to configure the servlet with `setAsyncSupported(true)`.

But, when I add this, I can't get `AsyncResponse` working with camel-cxf. There's an old issue here which seems to suggest that it's not supported:

https://issues.apache.org/jira/browse/CAMEL-7750

I can't find any test coverage in the Camel codebase for this scenario either.

What could work in a future WildFly-Camel release is something like:

```
    <jaxrs:server id="jaxrsServer" address="http://localhost:8080/services">
        <jaxrs:serviceBeans>
            <ref bean="asyncService"/>
        </jaxrs:serviceBeans>
        <jaxrs:providers>
            <ref bean="jacksonProvider"/>
        </jaxrs:providers>
    </jaxrs:server>
```

Which would give you a plain async CXF endpoint.

**Comment by anbeng** [comment]
Thank you for the feedback James. 

Will do further reading up on the camel cxf components to see if there is any other way to get the async cxf call working in camel. 

I also came across the issue below, which I assume resulted in performInvocation option

https://issues.apache.org/jira/plugins/servlet/mobile#issue/CAMEL-8205

"Starting from Camel 2.15, if a performInvocation option is enabled, the service implementation will be invoked first, the response will be set on the Camel exchange and the route execution will continue as usual. This can be useful for integrating the existing JAX-RS implementations into Camel routes and for post-processing JAX-RS Responses in custom processors."

http://camel.apache.org/cxfrs.html

Will see if I can get the jaxrs:server + asyncResponse + performInvocation working together but not sure if I will run into the same issue or how the option will behave in an async scenario but will test.
