### ISSUE TITLE
Intermittent failure of PGEventIntegrationTest

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2505]
Happens consistently on my laptop. At the same time I see `PGEventIntegrationTest` to pass consistently when run alone via `-Dtest=PGEventIntegrationTest`. 

It passes sometimes (when run together with other test classes) when I put Thread.sleep(5000) at the beginning of the actual test method. Maybe container does not report the readiness properly, or the container is a bit busy after startup.

**Comment by ppalaga** [comment]
@tdiesler says it also fails here quite regularly https://fabric8-ci.fusesource.com/view/wildfly-camel/job/wildfly-camel-stability/

**Comment by jamesnetherton** [comment]
Here's the error, seems the DB server is not fully initialised when the test is run:

```
14:16:24,507 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (pool-8-thread-1) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: IJ031084: Unable to create connection
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:345)
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:352)
	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287)
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1327)
	at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:499)
	at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:632)
	at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:604)
	at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624)
	at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:430)
	at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:789)
	at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
	at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:64)
	at org.apache.camel.component.pgevent.PgEventEndpoint.initJdbc(PgEventEndpoint.java:87)
	at org.apache.camel.component.pgevent.PgEventProducer.doStart(PgEventProducer.java:67)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.impl.DeferServiceStartupListener.onCamelContextStarted(DeferServiceStartupListener.java:49)
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3861)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3640)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3492)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:209)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3251)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3247)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3270)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3247)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3163)
	at org.wildfly.camel.test.pgevent.PGEventIntegrationTest.testPGEventComponent(PGEventIntegrationTest.java:119)

```

**Comment by jamesnetherton** [comment]
Somewhat sneaky of the postgres docker image to do a restart of the DBMS during the startup process. Unfortunately our Arquillian Cube config checks for container rediness against a log message of 'database system is ready'.
```
waiting for server to start....2018-05-02 13:28:10.874 UTC [35] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2018-05-02 13:28:10.874 UTC [35] LOG:  could not bind IPv6 address "::1": Address not available
2018-05-02 13:28:10.874 UTC [35] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2018-05-02 13:28:10.963 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-05-02 13:28:11.120 UTC [36] LOG:  database system was shut down at 2018-05-02 13:28:10 UTC
2018-05-02 13:28:11.166 UTC [35] LOG:  database system is ready to accept connections
 done
server started
ALTER ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2018-05-02 13:28:11.271 UTC [35] LOG:  received fast shutdown request
2018-05-02 13:28:11.321 UTC [35] LOG:  aborting any active transactions
2018-05-02 13:28:11.322 UTC [35] LOG:  worker process: logical replication launcher (PID 42) exited with exit code 1
2018-05-02 13:28:11.322 UTC [37] LOG:  shutting down
2018-05-02 13:28:11.651 UTC [35] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2018-05-02 13:28:11.723 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2018-05-02 13:28:11.723 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2018-05-02 13:28:11.812 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-05-02 13:28:11.981 UTC [46] LOG:  database system was shut down at 2018-05-02 13:28:11 UTC
2018-05-02 13:28:12.029 UTC [1] LOG:  database system is ready to accept connections
```
