### ISSUE TITLE
Automate the release of wildfly-camel docker images 

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#252]
Two options here:

Setup build jobs on hub.docker.com to build from a specified github repo tag which we can tweak and trigger on each release. We'd need a Dockerfile which could fetch any required release artifacts from nexus. 

Or:

Create a Jenkins job that can build wildfly-camel from a given release tag, create the relevant docker images, tag them and then push to dockerhub. This would require firewall changes on all build slaves (hence my preference of the first option).

**Comment by tdiesler** [comment]
Reverting - results in 

```
[INFO] --- docker-maven-plugin:0.11.2:build (build-wildfly-camel-images) @ wildfly-camel-docker ---
[INFO] DOCKER> Creating image [wildflyext/wildfly-camel]
[INFO] Copying files to /Users/tdiesler/git/wildfly-camel/docker/target/docker/wildflyext/wildfly-camel/build/maven
[INFO] Building tar: /Users/tdiesler/git/wildfly-camel/docker/target/docker/wildflyext/wildfly-camel/tmp/docker-build.tar
[WARNING] When creating tar entry
org.codehaus.plexus.archiver.ArchiverException: Problem writing to output in xAR operation request to write '8192' bytes exceeds size in header of '77987840' bytes for entry 'wildflyext/wildfly-camel/tmp/docker-build.tar'
	at org.codehaus.plexus.archiver.util.Streams.copyFullyDontCloseOutput(Streams.java:122)
	at org.codehaus.plexus.archiver.tar.TarArchiver.tarFile(TarArchiver.java:335)
	at org.codehaus.plexus.archiver.tar.TarArchiver.execute(TarArchiver.java:188)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:930)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createTarball(DockerAssemblyManager.java:110)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createDockerTarArchive(DockerAssemblyManager.java:78)
	at org.jolokia.docker.maven.BuildMojo.buildImage(BuildMojo.java:82)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:64)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:125)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

**Comment by tdiesler** [comment]
BTW, do we even need to do that? I'd think it "automates" < 5% of the release procedure.

**Comment by jamesnetherton** [comment]
Yes, true. Maybe there's not much value to be had here....

IIRC this issue was instigated from some troubles that we had with image pushing on the last release.

IMO the entire release process should be 'push button' from Jenkins, but that's an argument for another day......

**Comment by jamesnetherton** [comment]
Wont fix... no major value to be had here at this point in time.

This can always be resurrected in a later iteration if need be.

**Comment by tdiesler** [comment]
The manual process of releasing the docker images is tedious. Perhaps some  assistance can be given i.e. some commands that are documented in the [release procedure](https://github.com/wildfly-extras/wildfly-camel/wiki/Release-Procedure) wiki
