### ISSUE TITLE
BoxIntegrationTest fails with WildFly 13.0.0.Final

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2564]
https://ci.fabric8.io/job/wildfly-camel-pullreq/1579/testReport/org.wildfly.camel.test.box/BoxIntegrationTest/testBoxComponent/

```
org.wildfly.camel.test.box.BoxIntegrationTest.testBoxComponent: java.lang.NoClassDefFoundError: org/w3c/dom/css/CSSRule
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.process(AbstractJavaScriptConfiguration.java:183)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(AbstractJavaScriptConfiguration.java:147)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.buildUsageMap(AbstractJavaScriptConfiguration.java:79)
	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(AbstractJavaScriptConfiguration.java:59)
	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(JavaScriptConfiguration.java:597)
	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(JavaScriptConfiguration.java:613)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(JavaScriptEngine.java:132)
	at com.gargoylesoftware.htmlunit.WebClient.init(WebClient.java:240)
	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:214)
	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:205)
	at org.apache.camel.component.box.internal.BoxConnectionHelper.createStandardAuthenticatedConnection(BoxConnectionHelper.java:102)
	at org.apache.camel.component.box.internal.BoxConnectionHelper.createConnection(BoxConnectionHelper.java:91)
	at org.apache.camel.component.box.BoxComponent.doStart(BoxComponent.java:85)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3705)
	at org.apache.camel.impl.DefaultCamelContext.startServices(DefaultCamelContext.java:3711)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3442)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:209)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3253)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3249)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3272)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3249)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3165)
	at org.wildfly.camel.test.box.BoxIntegrationTest.testBoxComponent(BoxIntegrationTest.java:93)
```

**Comment by ppalaga** [comment]
Milestone should be 7.0.0 if that's with WF13, should it not?

**Comment by jamesnetherton** [comment]
Yep - only just got around to changing the milestone name.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/wildfly-extras/wildfly-camel/commit/2bb9cc10776477d60f17b4deeeccc8c776ccaca9.
