### ISSUE TITLE
NPE in CamelDeploymentSettings when deploying an EAR with two WARs 

### ISSUE THREAD

**Issue by ppalaga** [wildfly-extras/wildfly-camel#2580]
```
14:24:38,489 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."CXFWSEarBasicSecureProducerIntegrationTest.ear".DEPENDENCIES: org.jboss.msc.service.StartException in service jboss.deployment.unit."CXFWSEarBasicSecureProducerIntegrationTest.ear".DEPENDENCIES: WFLYSRV0153: Failed to process phase DEPENDENCIES of deployment "CXFWSEarBasicSecureProducerIntegrationTest.ear"
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:150)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
        at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.wildfly.extension.camel.deployment.CamelDeploymentSettings.isEnabled(CamelDeploymentSettings.java:60)
        at org.wildfly.extension.camel.deployment.CamelIntegrationProcessor.deploy(CamelIntegrationProcessor.java:45)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:143)
        ... 8 more
```

CamelDeploymentSettings.java:60 is `if (childDepSettings.isEnabled()) {` and we do not set `childDepSettings` anywhere except the initializer. Looks like a not completely intialized instance of `CamelDeploymentSettings` is leaking to another thread.

**Comment by jamesnetherton** [comment]
This isn't fixed. This problem still pops up occasionally.

**Comment by ppalaga** [comment]
@jamesnetherton could you please point me to a stacktrace to see where exactly it happened?

**Comment by jamesnetherton** [comment]
It's the same stacktrace as you posted in the first comment.

**Comment by ppalaga** [comment]
With which bits, which job did it happen? I'd need some reproducibility pointers.

**Comment by jamesnetherton** [comment]
Something I'm working on locally. Just a standard Camel CDI EAR deployment with 2 WAR modules.

Here's what my deployment looks like:

```java
    @Deployment(testable = false, name = "context-inject.ear")
    public static EnterpriseArchive createEarDeployment() {
        return ShrinkWrap.create(EnterpriseArchive.class, "context-inject.ear")
            .addAsModule(ShrinkWrap.create(WebArchive.class, "context-inject-a.war")
                .addClasses(CamelContextInjectionClassLoaderRecorderA.class, TestUtils.class)
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml")
                .setManifest(() -> {
                    ManifestBuilder builder = new ManifestBuilder();
                    builder.addManifestHeader("Dependencies", "org.jboss.modules");
                    return builder.openStream();
                })
            )
            .addAsModule(ShrinkWrap.create(WebArchive.class, "context-inject-b.war")
                .addClasses(CamelContextInjectionClassLoaderRecorderB.class, TestUtils.class)
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml")
                .setManifest(() -> {
                    ManifestBuilder builder = new ManifestBuilder();
                    builder.addManifestHeader("Dependencies", "org.jboss.modules");
                    return builder.openStream();
                })
            );
    }
```

**Comment by jamesnetherton** [comment]
It's mostly the same:
```
Caused by: java.lang.NullPointerException
	at org.wildfly.extension.camel.deployment.CamelDeploymentSettings.isEnabled(CamelDeploymentSettings.java:60)
	at org.wildfly.extension.camel.deployment.CamelIntegrationProcessor.deploy(CamelIntegrationProcessor.java:45)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:144)
	... 8 more
```

I think the `CamelDeploymentSettings` attachment is a bit flawed for EAR deployments. When the parent EAR deployment calls `CamelDeploymentSettings.isEnabled()`, there's no guarantee that the child deployments have started deploying, or have even made it far enough in the deployment chain to have populated their own `CamelDeploymentSettings`.

**Comment by jamesnetherton** [comment]
Locking does seem to help. I've done 1000+ deployments and not seen the issue.

I'll add the changes with the stuff I'm working for #2497.
