### ISSUE TITLE
Missing hapi-structures dependencies in module ca.uhn.hapi 

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2611]
All of the hapi-structures dependencies for camel-hl7 are now optional, which means they never get added to the distro without us adding them into one of our own feature pack POMs. 

If you run tests with DEBUG logging, there are a bunch of NCDFEs thrown:
```
08:21:33,644 DEBUG [org.apache.camel.impl.converter.AnnotationTypeConverterLoader] (pool-8-thread-1) Ignoring converter type: org.apache.camel.component.hl7.HL721Converter as a dependent class could not be found: java.lang.NoClassDefFoundError: ca/uhn/hl7v2/model/v21/message/ACK: java.lang.NoClassDefFoundError: ca/uhn/hl7v2/model/v21/message/ACK
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.apache.camel.impl.converter.AnnotationTypeConverterLoader.loadConverterMethods(AnnotationTypeConverterLoader.java:262)
	at org.apache.camel.impl.converter.AnnotationTypeConverterLoader.load(AnnotationTypeConverterLoader.java:130)
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.loadTypeConverters(BaseTypeConverterRegistry.java:640)
	at org.apache.camel.impl.converter.DefaultTypeConverter.doStart(DefaultTypeConverter.java:62)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)

```

**Comment by jamesnetherton** [comment]
Needs [CAMEL-12697](https://issues.apache.org/jira/browse/CAMEL-12697) to implement fully.
