### ISSUE TITLE
Module camel-rss exposes com.sun.syndication

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#272]
Module org.apache.camel.component.rss incorrectly exports com.sun.syndication packages. These should be an implementation detail of camel-rss

**Comment by tdiesler** [comment]
```
13:38:05,211 WARN  [org.apache.camel.component.rss.RssEntryPollingConsumer] (Camel (camel-2) thread #0 - rss://https://developer.jboss.org/blogs/feeds/posts) Consumer Consumer[rss://https://developer.jboss.org/blogs/feeds/posts?splitEntries=true] failed polling endpoint: Endpoint[rss://https://developer.jboss.org/blogs/feeds/posts?splitEntries=true]. Will try again at next poll. Caused by: [java.lang.ExceptionInInitializerError - null]: java.lang.ExceptionInInitializerError
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
	at org.apache.camel.component.rss.RssUtils.createFeed(RssUtils.java:34) [camel-rss-2.14.1.jar:2.14.1]
	at org.apache.camel.component.rss.RssEntryPollingConsumer.createFeed(RssEntryPollingConsumer.java:54) [camel-rss-2.14.1.jar:2.14.1]
	at org.apache.camel.component.feed.FeedEntryPollingConsumer.poll(FeedEntryPollingConsumer.java:47) [camel-atom-2.14.1.jar:2.14.1]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:187) [camel-core-2.14.1.jar:2.14.1]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:114) [camel-core-2.14.1.jar:2.14.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_31]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [rt.jar:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_31]
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434) [rt.jar:1.8.0_31]
	at java.util.Properties.load0(Properties.java:353) [rt.jar:1.8.0_31]
	at java.util.Properties.load(Properties.java:341) [rt.jar:1.8.0_31]
	at com.sun.syndication.io.impl.PropertiesLoader.<init>(PropertiesLoader.java:74)
	at com.sun.syndication.io.impl.PropertiesLoader.getPropertiesLoader(PropertiesLoader.java:46)
	at com.sun.syndication.io.impl.PluginManager.<init>(PluginManager.java:54)
	at com.sun.syndication.io.impl.PluginManager.<init>(PluginManager.java:46)
	at com.sun.syndication.feed.synd.impl.Converters.<init>(Converters.java:40)
	at com.sun.syndication.feed.synd.SyndFeedImpl.<clinit>(SyndFeedImpl.java:59)
```
This is because of rome PropertiesLoader

```
    public static PropertiesLoader getPropertiesLoader() {
        synchronized(PropertiesLoader.class) {
            PropertiesLoader loader = (PropertiesLoader)
                clMap.get(Thread.currentThread().getContextClassLoader());
            if (loader == null) {
                try {
                    loader = new PropertiesLoader(MASTER_PLUGIN_FILE, EXTRA_PLUGIN_FILE);
                    clMap.put(Thread.currentThread().getContextClassLoader(), loader);
                }
                catch (IOException ex) {
                    throw new RuntimeException(ex);
                }
            }
            return loader;
        }
    }
```
