### ISSUE TITLE
Intermittent failure of KafkaConsumerIntegrationTest

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2736]
```
&amp#27;[0m&amp#27;[0m06:12:36,717 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "kafka-consumer-tests.jar" (runtime-name : "kafka-consumer-tests.jar")
&amp#27;[0m### Embedded Zookeeper connection: localhost:1110
EmbeddedKafkaBroker: local directory: /tmp/kafka-local4593846
2019-01-08 06:12:39 WARN  [kafka.server.BrokerMetadataCheckpoint] (main2019-01-08 06:12:39 WARN  [kafka.server.BrokerMetadataCheckpoint] (main2019-01-08 06:12:45 WARN  [org.apache.zookeeper.ClientCnxn] (main-SendThread(localhost:1110)2019-01-08 06:12:45 WARN  [org.apache.zookeeper.server.NIOServerCnxn] (NIOServerCxn.Factory:localhost/127.0.0.1:11102019-01-08 06:12:47 WARN  [org.apache.zookeeper.ClientCnxn] (main-SendThread(localhost:1110)2019-01-08 06:12:47 ERROR [kafka.controller.KafkaController] (controller-event-threadorg.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /brokers/topics
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:130) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
	at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:492) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient.getAllTopicsInCluster(KafkaZkClient.scala:354) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.controller.KafkaController.initializeControllerContext(KafkaController.scala:653) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:239) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.controller.KafkaController.kafka$controller$KafkaController$$elect(KafkaController.scala:1214) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.controller.KafkaController$Startup$.process(KafkaController.scala:1148) [kafka_2.11-2.0.0.jar:na]
	at kafka.controller.ControllerEventManager$ControllerEventThread$$anonfun$doWork$1.apply$mcV$sp(ControllerEventManager.scala:86) [kafka_2.11-2.0.0.jar:na]
	at kafka.controller.ControllerEventManager$ControllerEventThread$$anonfun$doWork$1.apply(ControllerEventManager.scala:86) [kafka_2.11-2.0.0.jar:na]
	at kafka.controller.ControllerEventManager$ControllerEventThread$$anonfun$doWork$1.apply(ControllerEventManager.scala:86) [kafka_2.11-2.0.0.jar:na]
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31) [kafka_2.11-2.0.0.jar:na]
	at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:85) [kafka_2.11-2.0.0.jar:na]
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82) [kafka_2.11-2.0.0.jar:na]
2019-01-08 06:12:47 ERROR [kafka.server.KafkaServer] (mainorg.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /brokers/topics/__transaction_state
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:130) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
	at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:492) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient$$anonfun$getReplicaAssignmentForTopics$1.apply(KafkaZkClient.scala:468) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient$$anonfun$getReplicaAssignmentForTopics$1.apply(KafkaZkClient.scala:463) ~[kafka_2.11-2.0.0.jar:na]
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104) ~[scala-library-2.11.7.jar:na]
	at kafka.zk.KafkaZkClient.getReplicaAssignmentForTopics(KafkaZkClient.scala:463) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient.getTopicPartitionCount(KafkaZkClient.scala:513) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.coordinator.transaction.TransactionStateManager.getTransactionTopicPartitionCount(TransactionStateManager.scala:285) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.coordinator.transaction.TransactionStateManager.<init>(TransactionStateManager.scala:97) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.coordinator.transaction.TransactionCoordinator$.apply(TransactionCoordinator.scala:58) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.server.KafkaServer.startup(KafkaServer.scala:279) ~[kafka_2.11-2.0.0.jar:na]
	at org.wildfly.camel.test.common.kafka.EmbeddedKafkaBroker.startBroker(EmbeddedKafkaBroker.java:138) [wildfly-camel-itests-common-9.1.0-SNAPSHOT.jar:na]
	at org.wildfly.camel.test.common.kafka.EmbeddedKafkaBroker.startup(EmbeddedKafkaBroker.java:121) [wildfly-camel-itests-common-9.1.0-SNAPSHOT.jar:na]
	at org.wildfly.camel.test.kafka.KafkaConsumerIntegrationTest.before(KafkaConsumerIntegrationTest.java:75) [test-classes/:na]
```

**Comment by jamesnetherton** [comment]
Closing as I've not seen this occur for a while now.
