### ISSUE TITLE
Intermittent failure of KafkaProducerIntegrationTest

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2737]
```
&amp#27;[0m&amp#27;[0m06:12:15,502 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "kafka-producer-tests.jar" (runtime-name : "kafka-producer-tests.jar")
&amp#27;[0m### Embedded Zookeeper connection: localhost:1109
EmbeddedKafkaBroker: local directory: /tmp/kafka-local1491408
2019-01-08 06:12:23 WARN  [kafka.server.BrokerMetadataCheckpoint] (main2019-01-08 06:12:30 WARN  [org.apache.zookeeper.ClientCnxn] (main-SendThread(localhost:1109)2019-01-08 06:12:30 WARN  [org.apache.zookeeper.server.NIOServerCnxn] (NIOServerCxn.Factory:localhost/127.0.0.1:11092019-01-08 06:12:33 WARN  [org.apache.zookeeper.ClientCnxn] (main-SendThread(localhost:1109)2019-01-08 06:12:33 ERROR [kafka.server.KafkaServer] (mainkafka.zookeeper.ZooKeeperClientExpiredException: Session expired either before or while waiting for connection
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:238) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:226) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zookeeper.ZooKeeperClient$$anonfun$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:220) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zookeeper.ZooKeeperClient$$anonfun$waitUntilConnected$1.apply(ZooKeeperClient.scala:220) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zookeeper.ZooKeeperClient$$anonfun$waitUntilConnected$1.apply(ZooKeeperClient.scala:220) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:219) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient.retryRequestsUntilConnected(KafkaZkClient.scala:1503) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient.kafka$zk$KafkaZkClient$$retryRequestUntilConnected(KafkaZkClient.scala:1479) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient.getChildren(KafkaZkClient.scala:584) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient.getSortedBrokerList(KafkaZkClient.scala:343) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.zk.KafkaZkClient.getAllBrokersInCluster(KafkaZkClient.scala:310) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.server.KafkaServer.createBrokerInfo(KafkaServer.scala:382) ~[kafka_2.11-2.0.0.jar:na]
	at kafka.server.KafkaServer.startup(KafkaServer.scala:256) ~[kafka_2.11-2.0.0.jar:na]
	at org.wildfly.camel.test.common.kafka.EmbeddedKafkaBroker.startBroker(EmbeddedKafkaBroker.java:138) [wildfly-camel-itests-common-9.1.0-SNAPSHOT.jar:na]
	at org.wildfly.camel.test.common.kafka.EmbeddedKafkaBroker.startup(EmbeddedKafkaBroker.java:121) [wildfly-camel-itests-common-9.1.0-SNAPSHOT.jar:na]
	at org.wildfly.camel.test.kafka.KafkaProducerIntegrationTest.before(KafkaProducerIntegrationTest.java:85) [test-classes/:na]

```

**Comment by jamesnetherton** [comment]
Closing as I've not seen this occur for a while now.
