### ISSUE TITLE
GPRC DNS name resolution fails

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2757]
Happens during server setup (i.e. on the surefire client side) with camel-2.23.1 on eap-7.2 and prevents the GRPCIntegrationTest to run.

```
09:59:28,394 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "camel-grpc-tests.jar" (runtime-name : "camel-grpc-tests.jar")
09:59:28,760 INFO  [org.jboss.arquillian.testenricher.cdi.container.BeanManagerProducer] (pool-8-thread-2) BeanManager not found.
09:59:28,908 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-8-thread-2) Apache Camel 2.23.1 (CamelContext: camel-1) is starting
09:59:28,910 INFO  [org.apache.camel.management.ManagedManagementStrategy] (pool-8-thread-2) JMX is enabled
09:59:28,977 INFO  [org.wildfly.extension.camel] (pool-8-thread-2) Camel context starting: camel-1
09:59:28,977 INFO  [org.wildfly.extension.camel] (MSC service thread 1-1) Bound camel naming object: java:jboss/camel/context/camel-1
09:59:29,915 INFO  [org.apache.camel.impl.converter.DefaultTypeConverter] (pool-8-thread-2) Type converters loaded (core: 195, classpath: 2786)
09:59:30,014 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-8-thread-2) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
09:59:30,016 INFO  [org.apache.camel.impl.HeadersMapFactoryResolver] (pool-8-thread-2) Detected and using custom HeadersMapFactory: org.apache.camel.component.headersmap.FastHeadersMapFactory@28a3631b
09:59:30,041 INFO  [org.apache.camel.component.grpc.GrpcProducer] (pool-8-thread-2) Creating channel to the remote gRPC server localhost:1100
09:59:30,173 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-8-thread-2) Route: route1 started and consuming from: direct://start
09:59:30,174 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-8-thread-2) Total 1 routes, of which 1 are started
09:59:30,175 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-8-thread-2) Apache Camel 2.23.1 (CamelContext: camel-1) started in 1.268 seconds
09:59:30,223 ERROR [stderr] (grpc-default-executor-0) Exception in thread "grpc-default-executor-0" java.lang.AssertionError
09:59:30,223 ERROR [stderr] (grpc-default-executor-0) 	at io.grpc.internal.DnsNameResolver.getResourceResolver(DnsNameResolver.java:529)
09:59:30,223 ERROR [stderr] (grpc-default-executor-0) 	at io.grpc.internal.DnsNameResolver.access$500(DnsNameResolver.java:59)
09:59:30,223 ERROR [stderr] (grpc-default-executor-0) 	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:206)
09:59:30,224 ERROR [stderr] (grpc-default-executor-0) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:59:30,224 ERROR [stderr] (grpc-default-executor-0) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:59:30,224 ERROR [stderr] (grpc-default-executor-0) 	at java.lang.Thread.run(Thread.java:748)
09:59:35,187 INFO  [org.apache.camel.impl.DefaultCamelContext] (pool-8-thread-2) Apache Camel 2.23.1 (CamelContext: camel-1) is shutting down
09:59:35,210 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (pool-8-thread-2) Starting to graceful shutdown 1 routes (timeout 300 seconds)
09:59:35,213 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (camel-1) thread #2 - ShutdownTask) Waiting as there are still 1 inflight and pending exchanges to complete, timeout in 300 seconds. Inflights per route: [route1 = 1]
09:59:35,216 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (camel-1) thread #2 - ShutdownTask) There are 1 inflight exchanges:
	InflightExchange: [exchangeId=ID-MacBook-1549011568814-0-1, fromRouteId=route1, routeId=route1, nodeId=to1, elapsed=0, duration=5024]
09:59:36,218 INFO  [org.apache.camel.impl.DefaultShutdownStrategy] (Camel (camel-1) thread #2 - ShutdownTask) Waiting as there are still 1 inflight and pending exchanges to complete, timeout in 299 seconds. Inflights per route: [route1 = 1]
```

**Comment by tdiesler** [comment]
You can debug the setup like this 

```
mvn clean install -Dtest=GRPCIntegrationTest -DargLine=-agentlib:jdwp=transport=dt_socket,address=5001,server=y,suspend=y
```

**Comment by tdiesler** [comment]
Fixed by

```
<module xmlns="urn:jboss:module:1.3" name="sun.jdk.ext">
    <dependencies>
        <system export="true">
            <paths>
                <!-- default DOM impl lookup -->
                <path name="com/sun/org/apache/xerces/internal/dom" />
                <!-- needed by castor -->
                <path name="com/sun/org/apache/xml/internal/serialize" />
                <!-- needed by grpc-->
                <path name="com/sun/jndi/dns" />
                <!-- needed by hadoop -->
                <path name="com/sun/security/auth/module" />
            </paths>
        </system>
    </dependencies>
</module>
```
