### ISSUE TITLE
Spring based deployments no longer work with Camel3

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2802]
```
mvn clean install -Dtest=SpringBeanTransformTest

org.apache.camel.RoutesBuilder is an interface, and JAXB can't handle interfaces.
	this problem is related to the following location:
		at org.apache.camel.RoutesBuilder
		at private java.util.List org.apache.camel.core.xml.AbstractCamelContextFactoryBean.builders
		at org.apache.camel.core.xml.AbstractCamelContextFactoryBean
		at org.apache.camel.spring.CamelContextFactoryBean
```

**Comment by tdiesler** [comment]
```
SEVERE: Failed: org.wildfly.camel.test.spring.SpringBeanTransformTest.testSpringContextFromURL
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to create the JAXB binder; nested exception is org.jboss.arquillian.test.spi.ArquillianProxyException: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException : 39 counts of IllegalAnnotationExceptions [Proxied because : Original exception caused: class java.io.NotSerializableException: com.sun.xml.bind.v2.model.nav.ReflectionNavigator$7]
	at org.apache.camel.spring.handler.CamelNamespaceHandler$CamelContextBeanDefinitionParser.doParse(CamelNamespaceHandler.java:347)
	at org.springframework.beans.factory.xml.AbstractSingleBeanDefinitionParser.parseInternal(AbstractSingleBeanDefinitionParser.java:88)
	at org.springframework.beans.factory.xml.AbstractBeanDefinitionParser.parse(AbstractBeanDefinitionParser.java:63)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1366)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1352)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:179)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:149)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:96)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:513)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:393)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.wildfly.camel.utils.SpringCamelContextBootstrap.loadBeanDefinitions(SpringCamelContextBootstrap.java:172)
	at org.wildfly.camel.utils.SpringCamelContextBootstrap.<init>(SpringCamelContextBootstrap.java:72)
	at org.wildfly.camel.utils.SpringCamelContextBootstrap.<init>(SpringCamelContextBootstrap.java:60)
	at org.wildfly.camel.utils.SpringCamelContextFactory.createSingleCamelContext(SpringCamelContextFactory.java:46)
	at org.wildfly.camel.test.spring.SpringBeanTransformTest.testSpringContextFromURL(SpringBeanTransformTest.java:62)
```

**Comment by tdiesler** [comment]
After some JAXB debugging it turns out that on WildFly16 (with jaxb-2.3.1) attribute template is not ignored which leads to JAXB complaining that ConsumerTemplate is an interface.

```
@XmlAccessorType(XmlAccessType.FIELD)
public abstract class AbstractCamelConsumerTemplateFactoryBean extends AbstractCamelFactoryBean<ConsumerTemplate> {

    @XmlTransient
    private ConsumerTemplate template;
    @XmlAttribute @Metadata(description = "Sets a custom maximum cache size to use in the backing cache pools.")
    private Integer maximumCacheSize;
```
