### ISSUE TITLE
Cannot resolve optaplanner endpoint

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2811]
```
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: optaplanner://optaplanner/solverConfig.xml due to: KieServices must be specified
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:769)
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:71)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:118)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:124)
```

**Comment by jamesnetherton** [comment]
I took a very brief look at this. I think the problem is [here](https://github.com/kiegroup/droolsjbpm-knowledge/blob/5d94d78d415a3f71a28389be8b422a5a9a629944/kie-api/src/main/java/org/kie/api/internal/utils/ServiceDiscoveryImpl.java#L156-L161):

```
    private Optional<KieConfs> getKieConfs() {
        return Stream.of(this.getClass().getClassLoader(), Thread.currentThread().getContextClassLoader(), ClassLoader.getSystemClassLoader())
                .map(this::loadKieConfs)
                .filter( Objects::nonNull )
                .findFirst();
    }
```

Because of the `findFirst()`, the first `ClassLoader` to find `META-INF/kie.conf` resources wins. I.e only configs that are part of the `org.kie` module will ever be loaded. The missing service is part of the `org.drools` module.
