### ISSUE TITLE
Usage of camel-atom depends on TCCL

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#282]

**Comment by tdiesler** [comment]
With no TCCL we get 

```
11:13:12,175 WARN  [org.apache.camel.component.atom.AtomEntryPollingConsumer] (Camel (camel-2) thread #0 - atom://http://localhost:8080/atom-test/atom/feed) Consumer Consumer[atom://http://localhost:8080/atom-test/atom/feed?splitEntries=true] failed polling endpoint: Endpoint[atom://http://localhost:8080/atom-test/atom/feed?splitEntries=true]. Will try again at next poll. Caused by: [java.lang.RuntimeException - java.lang.NullPointerException]: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.abdera.util.Discover$DefaultLoader.init(Discover.java:108)
	at org.apache.abdera.util.Discover$DefaultLoader.<init>(Discover.java:91)
	at org.apache.abdera.util.Discover$DefaultLoader.<init>(Discover.java:85)
	at org.apache.abdera.util.Discover.locate(Discover.java:62)
	at org.apache.abdera.util.Discover.locate(Discover.java:54)
	at org.apache.abdera.util.AbderaConfiguration.loadExtensionFactories(AbderaConfiguration.java:100)
	at org.apache.abdera.util.AbderaConfiguration.<init>(AbderaConfiguration.java:92)
	at org.apache.abdera.util.AbderaConfiguration.<init>(AbderaConfiguration.java:87)
	at org.apache.abdera.util.AbderaConfiguration.getDefault(AbderaConfiguration.java:65)
	at org.apache.abdera.Abdera.<init>(Abdera.java:73)
	at org.apache.abdera.Abdera.getInstance(Abdera.java:57)
	at org.apache.camel.component.atom.AtomUtils.getAtomParser(AtomUtils.java:42)
	at org.apache.camel.component.atom.AtomUtils.parseDocument(AtomUtils.java:55)
	at org.apache.camel.component.atom.AtomEntryPollingConsumer.getDocument(AtomEntryPollingConsumer.java:43)
	at org.apache.camel.component.atom.AtomEntryPollingConsumer.createFeed(AtomEntryPollingConsumer.java:65)
	at org.apache.camel.component.feed.FeedEntryPollingConsumer.poll(FeedEntryPollingConsumer.java:47)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:187)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_31]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [rt.jar:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_31]
```

This is because Abdera has TCCL usage hard coded in Discover.getLoader()

```
    private static ClassLoader getLoader() {
        return Thread.currentThread().getContextClassLoader();
    }
```

**Comment by tdiesler** [comment]
Done
