### ISSUE TITLE
NsqIntegrationTest cannot access DOCKER_HOST

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2862]
There is this funky host name, which results from `TestUtils.getDockerHost()`

```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: MacBook3.fritz.box/192.168.178.30:4150
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Comment by tdiesler** [comment]
The DOCKER_HOST env var is not set because of the unix://... connection string that is used with Docker Desktop

**Comment by jamesnetherton** [comment]
Without having access to a Mac it's a little tricky for me to test & verify. If `DOCKER_HOST` is not set, then the default host name is taken from [`InetAddress.getLocalHost().getHostName()`](https://github.com/wildfly-extras/wildfly-camel/blob/master/itests/common/src/main/java/org/wildfly/camel/test/common/utils/TestUtils.java#L36).

**Comment by tdiesler** [comment]
```
[14:20:39]  <+tdiesler>	jnetherton, lets assume InetAddress.getLocalHost().getHostName() returns that funky hostname and lets further assume that this does not work with the nsq component URL
[14:21:00]  <+tdiesler>	BTW, with all other comps it seems to work
[14:21:13]  <+tdiesler>	shall we perhaps try the IP?
[14:21:28]  <+jnetherton>	yes, worth a try
[14:22:03]  <+tdiesler>	i.e. getHostAddress
[14:22:16]  <+tdiesler>	jnetherton, ok, let me try that real quick ...
```

**Comment by tdiesler** [comment]
Now I get

```
Connection refused: /192.168.178.30:4150
```
