### ISSUE TITLE
LdapIntegration fails with NoSuchFieldError: SESSION_SECURED

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2915]
```
2019-11-26 08:30:41 WARN  [org.apache.directory.server.ldap.LdapProtocolHandler] (pool-7-thread-1) - Unexpected exception forcing session to close: sending disconnect notice to client.
java.lang.NoSuchFieldError: SESSION_SECURED
	at org.apache.directory.server.ldap.LdapProtocolHandler.messageReceived(LdapProtocolHandler.java:182)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:1015)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:106)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:89)
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.runTask(UnorderedThreadPoolExecutor.java:541)
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.run(UnorderedThreadPoolExecutor.java:493)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tdiesler** [comment]
Done
