### ISSUE TITLE
CNFE ...jackson.annotation.JsonFormat$Feature

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2916]
Shows on wildfly-19.x
```
[ERROR] testServiceDiscovery(org.wildfly.camel.test.consul.ConsulIntegrationTest)  Time elapsed: 3.242 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonFormat$Feature
	at org.wildfly.camel.test.consul.ConsulIntegrationTest.testServiceDiscovery(ConsulIntegrationTest.java:175)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonFormat$Feature from [Module "com.fasterxml.jackson.datatype.guava" version 2.10.1 from local module loader @37e547da (finder: local module finder @2b6856dd (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/docker/target/wildfly-19.0.0.Beta1-SNAPSHOT/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/docker/target/wildfly-19.0.0.Beta1-SNAPSHOT/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/docker/target/wildfly-19.0.0.Beta1-SNAPSHOT/modules/system/layers/base))]
	at org.wildfly.camel.test.consul.ConsulIntegrationTest.testServiceDiscovery(ConsulIntegrationTest.java:175)
```

**Comment by tdiesler** [comment]
Done
