### ISSUE TITLE
Startup failure when Java Security Manager is enabled

### ISSUE THREAD

**Issue by jarek-przygodzki** [wildfly-extras/wildfly-camel#2932]
Trying to start the server with `-secmgr` flag fails with the following error:

```
09:56:44,989 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.wildfly.camel.ContextCreateHandlerRegistry: org.jboss.msc.service.StartException in service jboss.wildfly.camel.ContextCreateHandlerRegistry: Failed to start service
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731) [jboss-msc-1.4.11.Final.jar:1.4.11.Final]
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559) [jboss-msc-1.4.11.Final.jar:1.4.11.Final]
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at java.base/java.lang.Thread.run(Thread.java:834) [java.base:]
Caused by: java.lang.NoClassDefFoundError: org/wildfly/security/manager/action/GetContextClassLoaderAction
        at org.wildfly.extension.camel.cxf.undertow//org.apache.cxf.transport.undertow.wildfly.subsystem.extension.SecurityActions.getContextClassLoader(SecurityActions.java:41)
        at org.wildfly.extension.camel.cxf.undertow//org.apache.cxf.transport.undertow.wildfly.subsystem.extension.CxfDefaultBusHandler$CxfDefaultBusEndpointStrategy.<init>(CxfDefaultBusHandler.java:65)
        at org.wildfly.extension.camel.cxf.undertow//org.apache.cxf.transport.undertow.wildfly.subsystem.extension.CxfDefaultBusHandler.<init>(CxfDefaultBusHandler.java:48)
        at org.wildfly.extension.camel.cxf.undertow//org.apache.cxf.transport.undertow.wildfly.subsystem.extension.CxfSubsytemExtension.getContextCreateHandler(CxfSubsytemExtension.java:38)
        at org.wildfly.extension.camel//org.wildfly.extension.camel.service.ContextCreateHandlerRegistryService$ContextCreateHandlerRegistryImpl$1.accept(ContextCreateHandlerRegistryService.java:93)
        at org.wildfly.extension.camel//org.wildfly.extension.camel.service.ContextCreateHandlerRegistryService$ContextCreateHandlerRegistryImpl$1.accept(ContextCreateHandlerRegistryService.java:90)
        at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1032) [java.base:]
        at org.wildfly.extension.camel//org.wildfly.extension.camel.parser.SubsystemState.processExtensions(SubsystemState.java:95)
        at org.wildfly.extension.camel//org.wildfly.extension.camel.service.ContextCreateHandlerRegistryService$ContextCreateHandlerRegistryImpl.<init>(ContextCreateHandlerRegistryService.java:90)
        at org.wildfly.extension.camel//org.wildfly.extension.camel.service.ContextCreateHandlerRegistryService.start(ContextCreateHandlerRegistryService.java:71)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739) [jboss-msc-1.4.11.Final.jar:1.4.11.Final]
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701) [jboss-msc-1.4.11.Final.jar:1.4.11.Final]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.wildfly.security.manager.action.GetContextClassLoaderAction from [Module "org.wildfly.extension.camel.cxf.undertow" from local module loader @2ecf3cb (finder: local module finder @4850fc5e (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/fuse,/opt/wildfly/modules/system/layers/base,/opt/wildfly/modules/system/add-ons/keycloak))]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255) [jboss-modules.jar:1.9.1.Final]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410) [jboss-modules.jar:1.9.1.Final]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398) [jboss-modules.jar:1.9.1.Final]
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116) [jboss-modules.jar:1.9.1.Final]
        ... 18 more
```

Can be reproduced using Docker image
```
docker run --rm -it -e SECMGR=true wildflyext/wildfly-camel:11.0.0
```

**Comment by jamesnetherton** [comment]
Seems module `org.wildfly.extension.camel.cxf.undertow` is missing a dependency on `org.wildfly.security.elytron`.

**Comment by jarek-przygodzki** [comment]
Adding dependency from `org.wildfly.extension.camel.cxf.undertow` to `org.wildfly.security.elytron` dependency fixes this issue. Any chance it will be included in next release?

**Comment by jamesnetherton** [comment]
Yes, I'll fix it shortly for the next release.
