### ISSUE TITLE
Cannot find custom type converter with camel-3.1.x

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2951]
```
Caused by: org.apache.camel.NoTypeConversionAvailableException: No type converter available to convert from type: java.util.LinkedHashMap to the required type: org.wildfly.camel.test.common.types.Customer with value {firstName=John, lastName=Doe}
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.mandatoryConvertTo(BaseTypeConverterRegistry.java:224)
	at org.apache.camel.support.MessageSupport.getMandatoryBody(MessageSupport.java:116)
```

https://camel.apache.org/manual/latest/camel-3x-upgrade-guide.html#_package_scanning_typeconverter

CrossRef: https://issues.apache.org/jira/browse/CAMEL-14593

**Comment by tdiesler** [comment]
Done
