### ISSUE TITLE
Yammer integration fails with 401 on camel-3.1.x

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2952]
```
11:20:22,045 WARN  [org.apache.camel.component.yammer.YammerMessagePollingConsumer] (Camel (camel-1) thread #1 - yammer://messages) Consumer Consumer[yammer://messages?accessToken=xxxxxx&consumerKey=aConsumerKey&consumerSecret=aConsumerSecretKey] failed polling endpoint: yammer://messages?accessToken=xxxxxx&consumerKey=aConsumerKey&consumerSecret=aConsumerSecretKey. Will try again at next poll. Caused by: [java.lang.NullPointerException - null]: java.lang.NullPointerException
	at org.apache.camel.component.yammer.YammerMessagePollingConsumer.poll(YammerMessagePollingConsumer.java:120)
	at org.apache.camel.support.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:187)
	at org.apache.camel.support.ScheduledPollConsumer.run(ScheduledPollConsumer.java:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tdiesler** [comment]
Done, using a startup listener

```
        camelctx.addStartupListener((ctx, flag) -> {
            
            InputStream is = getClass().getResourceAsStream("/yammer/messages.json");
            String messages = camelctx.getTypeConverter().convertTo(String.class, is);

            Collection<Endpoint> endpoints = camelctx.getEndpoints();
            for (Endpoint endpoint : endpoints) {
                if (endpoint instanceof YammerEndpoint) {
                    ((YammerEndpoint)endpoint).getConfig().setRequestor(new TestApiRequestor(messages));
                }
            }
        });
```
