### ISSUE TITLE
Endpoint configurer fails with abstract component in camel-3.1.x

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#2953]
```
Caused by: org.apache.camel.component.hipchat.HipchatException: OAuth 2 auth token must be specified
	at org.apache.camel.component.hipchat.HipchatComponent.createEndpoint(HipchatComponent.java:55)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:240)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:779)
```

**Comment by tdiesler** [comment]
Done
