### ISSUE TITLE
EmbeddedCassandraServer fails to start on Java11

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#3048]
```
Caused by: org.apache.cassandra.exceptions.ConfigurationException: Expecting URI in variable: [cassandra.config]. Found[cassandra.yaml]. Please prefix the file with [file:///] for local files and [file://<server>/] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
	at org.apache.cassandra.config.YamlConfigurationLoader.getStorageConfigURL(YamlConfigurationLoader.java:80) ~[cassandra-all-3.7.jar:3.7]
	at org.apache.cassandra.config.YamlConfigurationLoader.<clinit>(YamlConfigurationLoader.java:94) ~[cassandra-all-3.7.jar:3.7]
```

**Comment by tdiesler** [comment]
out-of-date
