### ISSUE TITLE
Examples can no longer run standalone 

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#343]
```
[INFO] --- wildfly-maven-plugin:1.0.2.Final:start (wildfly-start) @ example-camel-rest ---
[INFO] JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
[INFO] JBOSS_HOME=/Users/tdiesler/git/wildfly-camel/examples/camel-rest/target/wildfly-8.2.0.Final

[INFO] Server is starting up.
Mar 02, 2015 9:41:02 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.2.2.Final
Listening for transport dt_socket at address: 8787
Mar 02, 2015 9:41:02 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.2.2.Final
Mar 02, 2015 9:41:03 AM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 4.0.3.Final
09:41:03,322 INFO  [org.jboss.modules] (main) JBoss Modules version 1.3.3.Final
java.lang.IllegalStateException: JBAS014805: Could not get main file: standalone-examples.xml. Specified files must be relative to the configuration dir: /Users/tdiesler/git/wildfly-camel/examples/camel-rest/target/wildfly-8.2.0.Final/standalone/configuration
	at org.jboss.as.controller.persistence.ConfigurationFile.determineMainFile(ConfigurationFile.java:167)
	at org.jboss.as.controller.persistence.ConfigurationFile.<init>(ConfigurationFile.java:94)
	at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:394)
	at org.jboss.as.server.Main.determineEnvironment(Main.java:262)
	at org.jboss.as.server.Main.main(Main.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
```

**Comment by jamesnetherton** [comment]
```mvn clean wildfly:run -Drun```

The way in which the examples area is structured is a mess IMO and should be refactored.

**Comment by tdiesler** [comment]
`mvn clean install` needs to continue to work in 2.2.0
