### ISSUE TITLE
Cannot obtain DOMImplementationRegistry instance

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#391]
```
Caused by: java.lang.ClassNotFoundException: com.sun.org.apache.xerces.internal.dom.DOMXSImplementationSourceImpl from [Module "deployment.hl7-tests:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final]
	at org.w3c.dom.bootstrap.DOMImplementationRegistry.newInstance(DOMImplementationRegistry.java:182) [rt.jar:1.8.0_31]
	at ca.uhn.hl7v2.util.XMLUtils.getDOMImpl(XMLUtils.java:52) [hapi-base-2.2.jar:]
```

CrossRef: https://issues.jboss.org/browse/WFLY-4416

**Comment by tdiesler** [comment]
A deployment cannot load the default DOM impl through the DOMImplementationRegistry because it has no wire to sun.jdk.

I wonder how the notion of the sun.jdk module works with other jdks. I'd assume that the internal paths are likely to be different.
