### ISSUE TITLE
Project does not build successfully on Windows

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#502]
Issues building on Windows are:

* Module checker script outputs Windows path format (E.g with "\") to module baseline file which then gives the impression that every module dependency has changed.

* Log4J surefire property in the itest module should start with file:/ (and not file://) else it leads to an exception being thrown.

```
log4j:ERROR Could not read configuration file from URL [file://C:/Users/james/projects/wildfly-camel/itests/standalone/src/test/resources/logging.properties].
java.net.UnknownHostException: C
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:157)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:943)
        at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:903)
```

* JAXB / SOAP integration test assertions fail during XML string comparison. Probably because of conversions of line endings (depends on how the git client or .gitattributes is configured).

**Comment by tdiesler** [comment]
Verified by: http://10.8.63.16/job/wildfly-camel-2.2-windows/
