### ISSUE TITLE
CXF cannot access springframework beans module

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#534]
```
Tests in error: 
  CXFSpringContextTest.org.wildfly.camel.test.cxf.CXFSpringContextTest » Deployment

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

```
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.BeansException from [Module "org.apache.cxf:main" from local module loader @2a70a3d8 (finder: local module finder @289d1c02 (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/target/wildfly-9.0.0.CR1-SNAPSHOT/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/target/wildfly-9.0.0.CR1-SNAPSHOT/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/target/wildfly-9.0.0.CR1-SNAPSHOT/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.4.2.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455) [jboss-modules.jar:1.4.2.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404) [jboss-modules.jar:1.4.2.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385) [jboss-modules.jar:1.4.2.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130) [jboss-modules.jar:1.4.2.Final]
	... 69 more
```

**Comment by jamesnetherton** [comment]
This will potentially be fixed once the latest smartics plugin version is incorporated into the build. We know that the CXF is missing several mandatory Spring dependencies including spring beans.

**Comment by tdiesler** [comment]
We are talking about the default wildfly-9.0.x CXF module that cannot see org/springframework/beans. AFAICS, smartics doesn't come into the game here

**Comment by tdiesler** [comment]
Done
