### ISSUE TITLE
JMS Example cannot find OrdersQueue

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#625]
This shows on branch 3.0

```
14:04:26,938 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "example-camel-jms-3.0.0-SNAPSHOT.war" (runtime-name : "example-camel-jms-3.0.0-SNAPSHOT.war")
WARN: can't find jboss-cli.xml. Using default configuration values.
May 15, 2015 2:04:26 PM org.jboss.as.cli.impl.CommandContextImpl printLine
INFO: The batch executed successfully
The batch executed successfully
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default) @ example-camel-jms ---
14:04:26,986 WARN  [org.apache.camel.component.jms.DefaultJmsMessageListenerContainer] (Camel (jms-cdi-context) thread #1 - JmsConsumer[OrdersQueue]) Setup of JMS message listener invoker failed for destination 'OrdersQueue' - trying to recover. Cause: HQ119017: Consumer is closed
14:04:26,989 INFO  [org.apache.camel.component.jms.DefaultJmsMessageListenerContainer] (Camel (jms-cdi-context) thread #1 - JmsConsumer[OrdersQueue]) Successfully refreshed JMS Connection
[INFO] Surefire report directory: /Users/tdiesler/git/wildfly-camel/examples/projects/camel-jms/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.wildfly.camel.examples.jms.JMSExampleTest
14:04:28,746 ERROR [org.apache.camel.processor.DefaultErrorHandler] (Camel (jms-cdi-context) thread #0 - file:///Users/tdiesler/git/wildfly-camel/examples/projects/camel-jms/target/wildfly-9.0.0.CR1/standalone/data/orders) Failed delivery for (MessageId: ID-localhost-49344-1431691466040-1-1 on ExchangeId: ID-localhost-49344-1431691466040-1-2). Exhausted after delivery attempt: 1 caught: org.springframework.jms.UncategorizedJmsException: Uncategorized exception occured during JMS processing; nested exception is javax.jms.JMSException: There is no queue with name OrdersQueue

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route1            ] [route1            ] [file:///Users/tdiesler/git/wildfly-camel/examples/projects/camel-jms/target/wi] [        12]
[route1            ] [convertBodyTo1    ] [convertBodyTo[java.lang.String]                                               ] [         3]
[route1            ] [removeHeaders1    ] [removeHeaders[*]                                                              ] [         0]
[route1            ] [to1               ] [jms:queue:OrdersQueue                                                         ] [         5]

Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-localhost-49344-1431691466040-1-2
	ExchangePattern     InOnly
	Headers             {CamelRedelivered=false, CamelRedeliveryCounter=0}
	BodyType            String
	Body                <?xml version="1.0" encoding="UTF-8"?><order>    <customer id="B0002">        <name>UK Customer</name>        <city>Test</city>        <country>UK</country>    </customer>    <orderlines>        <orderline>            <item id="001">                <description>Test</description>            </item>        </orderline>    </orderlines></order>
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------: org.springframework.jms.UncategorizedJmsException: Uncategorized exception occured during JMS processing; nested exception is javax.jms.JMSException: There is no queue with name OrdersQueue
	at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:316)
	at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:169)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:496)
	at org.apache.camel.component.jms.JmsConfiguration$CamelJmsTemplate.send(JmsConfiguration.java:235)
	at org.apache.camel.component.jms.JmsProducer.doSend(JmsProducer.java:413)
	at org.apache.camel.component.jms.JmsProducer.processInOnly(JmsProducer.java:367)
	at org.apache.camel.component.jms.JmsProducer.process(JmsProducer.java:153)
```

**Comment by tdiesler** [comment]
It seems that example-camel-jms.war is deployed before the cli script is executed - although the wildfly-maven-plugin suggests otherwise. 

Waiting on the client side before sending the first msg does not make a difference.
