### ISSUE TITLE
NullPointerException on RestletComponent.disconnect

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#651]
```
[0m[33m10:06:06,278 WARN  [org.apache.camel.impl.DefaultCamelContext] (pool-2-thread-1) Error occurred while shutting down service: org.apache.camel.impl.RouteService@3f760e97. This exception will be ignored.: 
java.lang.NullPointerException
	at org.apache.camel.component.restlet.RestletComponent.disconnect(RestletComponent.java:216) [camel-restlet-2.15.2.jar:2.15.2]
	at org.apache.camel.component.restlet.RestletEndpoint.disconnect(RestletEndpoint.java:125) [camel-restlet-2.15.2.jar:2.15.2]
	at org.apache.camel.component.restlet.RestletConsumer.doStop(RestletConsumer.java:86) [camel-restlet-2.15.2.jar:2.15.2]
	at org.apache.camel.support.ServiceSupport.stop(ServiceSupport.java:102) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.util.ServiceHelper.stopService(ServiceHelper.java:141) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.util.ServiceHelper.stopAndShutdownService(ServiceHelper.java:204) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.impl.RouteService.stopChildService(RouteService.java:359) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.impl.RouteService.doStop(RouteService.java:237) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.support.ChildServiceSupport.stop(ChildServiceSupport.java:77) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.support.ChildServiceSupport.stop(ChildServiceSupport.java:101) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.util.ServiceHelper.stopService(ServiceHelper.java:141) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.util.ServiceHelper.stopAndShutdownService(ServiceHelper.java:204) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.shutdownServices(DefaultCamelContext.java:2827) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.shutdownServices(DefaultCamelContext.java:2852) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.shutdownServices(DefaultCamelContext.java:2840) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.doStop(DefaultCamelContext.java:2675) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.support.ServiceSupport.stop(ServiceSupport.java:102) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72) [camel-core-2.15.2.jar:2.15.2]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2432) [camel-core-2.15.2.jar:2.15.2]
	at org.wildfly.camel.test.restlet.RestletConsumerIntegrationTest.testCxfRsConsumer(RestletConsumerIntegrationTest.java:59) [jaxrs-consumer-tests:]
```

CrossRef: https://issues.apache.org/jira/browse/CAMEL-8805

**Comment by tdiesler** [comment]
Blocked on camel-2.16.0

**Comment by tdiesler** [comment]
Blocked on camel-2.15.4
