### ISSUE TITLE
Unable to use DataSource defined in WildFly

### ISSUE THREAD

**Issue by simasch** [wildfly-extras/wildfly-camel#705]
Hi,

I'm trying to use camel-sql as described in the wiki book but it seams that camel is not looking in the JNDI context for the data source. I get

org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: java:jboss/datasources/prolixpro of type: javax.sql.DataSource

The root looks like this

.to("sql:" + SELECT + "?dataSource=java:jboss/datasources/prolixpro")

What is wrong?

Thanks, Simon

**Comment by jamesnetherton** [comment]
Hi,

This looks like a bug. Seems to work fine in our [integration test](https://github.com/wildfly-extras/wildfly-camel/blob/master/itests/standalone/src/main/java/org/wildfly/camel/test/sql/SQLIntegrationTest.java). But when I deployed an SQL route as a standalone war deployment, I hit the same problem as you describe.

I'll investigate further.

**Comment by simasch** [comment]
Is there a workaround? How can I pass the datasource to the SqlComponent?

**Comment by jamesnetherton** [comment]
If you're using CDI then you can try something like the following.

Create a class, into which you inject your datasource and have a producer method which is also annotated with `@Named`.

```java
public class DatasourceProducer {

    @Resource(name = "java:jboss/datasources/ExampleDS")
    DataSource dataSource;

    @Produces
    @Named("exampleDatasource")
    public DataSource getDataSource() {
        return dataSource;
    }
}
``` 

Then in your Camel route you can reference your datasource with whatever value you used in the `@Named` annotation:

```java
public class MyRouteBuilder extends RouteBuilder {

    @Override
    public void configure() throws Exception {
	from("sql:select name from information_schema.users?dataSource=exampleDatasource")
	.to("log:sql?showAll=true");
    }
}
```

Otherwise if you're using a Spring XML context, you should be able to use the `jee` namespace and pass the id as the dataSource parameter on the Camel endpoint.

```xml
<jee:jndi-lookup id="exampleDatasource" jndi-name="java:jboss/datasources/ExampleDS"/>
```

Still intrigued as to our integration test passes without doing any of this.....

**Comment by simasch** [comment]
I even get an issue with your workaround. It seams to take the default data source from WildFly that is H2. But I use Oracle.

```
Caused by: org.h2.jdbc.JdbcSQLException: Table "T_CUSTOMER" not found; SQL statement:
SELECT 'KSD' || CUSTOMER_NUMBER || LPAD(CUSTOMER_CATEGORY, 2, '0') || ' ' || RPAD(FIRM_COMPANYNAME, 35, ' ') || RPAD(NVL(FIRM_COMPANYNAME2, ' '), 35, ' ') || RPAD(NVL(PLZ, 0), 10, ' ') || RPAD(NVL(ORTSBEZ_18, ' '), 35, ' ') || RPAD('D', 1) || RPAD(NVL(ADDRESSES_STREET, ' '), 35) || RPAD('---', 3)  AS LINE FROM T_CUSTOMER JOIN T_FIRM ON CUSTOMER_FIRMID = FIRM_ID JOIN T_ADDRESSES ON CUSTOMER_DELIVERYADDRESSESID IS NOT NULL AND CUSTOMER_DELIVERYADDRESSESID = ADDRESSES_ID OR FIRM_DELIVRYADDRESSID = ADDRESSES_ID JOIN T_PLZ_FILE FPLZ ON ONRP = ADDRESSES_ONRP WHERE FIRM_ACTIVE = 1 [42102-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.Parser.readTableOrView(Parser.java:4864)
	at org.h2.command.Parser.readTableFilter(Parser.java:1107)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1713)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1821)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1707)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1550)
	at org.h2.command.Parser.parseSelect(Parser.java:1538)
	at org.h2.command.Parser.parsePrepared(Parser.java:405)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:644)
	at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.doPrepareStatement(BaseWrapperManagedConnection.java:745)
	at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.prepareStatement(BaseWrapperManagedConnection.java:731)
	at org.jboss.jca.adapters.jdbc.WrappedConnection.prepareStatement(WrappedConnection.java:405)
	at org.apache.camel.component.sql.SqlProducer$1.createPreparedStatement(SqlProducer.java:72) [camel-sql-2.15.0.jar:2.15.0]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:638)
```

**Comment by simasch** [comment]
I managed to get the workaround running by defining my datasource as default datasource in wildfly.

**Comment by jamesnetherton** [comment]
My bad. Slight error in my code example. The `@Resource` annotation should have used the `lookup` attribute and not `name`. Otherwise you just end up with the default datasource.

I tested this against a MariaDB instance and it worked fine.

```java
@Resource(lookup = "java:jboss/datasources/MariaDBTest")
```

**Comment by jamesnetherton** [comment]
Think I've worked out why the GitBook documentation example and the Integration test are working without any of the above changes.....

The integration test is using a `DefaultCamelContext` which internally creates a bean registry of type `JndiRegistry`. Hence the camel-sql endpoint can resolve a datasource directly from JNDI using configuration like `dataSource=java:jboss/datasources/ExampleDS`.

If you deploy an application to a container and use camel-cdi then you end up with a `CdiBeanRegistry` where the expectation is that you use CDI to wire beans into the bean registry.

If there is a bug here, I think it lies in our documentation. Camel is behaving as expected given the two different deployment scenarios (cdi vs non-cdi).

**Comment by simasch** [comment]
Now I understand the behavior and I close the issue. 

Thanks for the clarification!
