### ISSUE TITLE
ExportedPathsTest should ignore paths exported from org.wildfly.camel.extras

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#739]
For components like camel-sap, we get Jenkins to wire the component module into org.wildfly.camel.extras at build time. 

Since we're not always guaranteed to have this wiring on all test runs (E.g on runs where the SAP profile is not activated), the list of exported paths will be different and will result in the exported-paths.txt file being marked as a modified file.

**Comment by tdiesler** [comment]
```
java.lang.IllegalArgumentException: Module org.wildfly.camel.extras:main not found
	at org.jboss.modules.ModuleLoader$MXBeanImpl.loadModule(ModuleLoader.java:917)
	at org.jboss.modules.ModuleLoader$MXBeanImpl.getDependencies(ModuleLoader.java:828)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.jboss.as.jmx.PluggableMBeanServerImpl$TcclMBeanServer.invoke(PluggableMBeanServerImpl.java:1530)
	at org.jboss.as.jmx.PluggableMBeanServerImpl.invoke(PluggableMBeanServerImpl.java:748)
	at com.sun.jmx.mbeanserver.MXBeanProxy$InvokeHandler.invoke(MXBeanProxy.java:150)
	at com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:252)
	at com.sun.proxy.$Proxy26.getDependencies(Unknown Source)
	at org.wildfly.camel.test.classloading.ExportedPathsTest.setUp(ExportedPathsTest.java:123)
```
