### ISSUE TITLE
ClassNotFoundException: kafka.serializer.StringEncoder

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#775]
when using camel-2.16-SNAPSHOT

```
Caused by: java.lang.ClassNotFoundException: kafka.serializer.StringEncoder
	at org.apache.camel.impl.DefaultClassResolver.resolveMandatoryClass(DefaultClassResolver.java:80)
	at org.apache.camel.component.kafka.KafkaEndpoint.createProducer(KafkaEndpoint.java:83)
	at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:402)
```

camel-swagger is supposed to migrate off scala. This may be related to the two scala versions currently in use

**Comment by tdiesler** [comment]
Blocked on camel-2.16

**Comment by jamesnetherton** [comment]
This seems to have been verified as working for Kafka producers some time ago.

https://github.com/wildfly-extras/wildfly-camel/blob/master/itests/standalone/basic/src/main/java/org/wildfly/camel/test/kafka/KafkaIntegrationTest.java#L108

Unless this was failing in some other scenario, I'm going to close this.
