### ISSUE TITLE
Cannot resolve beanmapping XML Schema

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#844]
```
16:47:51,946 INFO  [org.apache.camel.impl.converter.DefaultTypeConverter] (pool-3-thread-2) Loaded 253 type converters
16:47:51,955 ERROR [org.dozer.loader.xml.DozerResolver] (pool-3-thread-2) Could not resolve beanmapping XML Schema [http://dozer.sourceforge.net/schema/beanmapping.xsd]: not found in classpath: java.lang.NullPointerException
	at org.dozer.loader.xml.DozerResolver.resolveEntity(DozerResolver.java:50)
	at org.apache.xerces.util.EntityResolverWrapper.resolveEntity(EntityResolverWrapper.java:107)
	at org.apache.xerces.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:695)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:624)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2699)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2079)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:788)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:283)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(XMLNSDocumentScannerImpl.java:733)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1754)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:875)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:798)
	at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
	at org.apache.xerces.parsers.DOMParser.parse(DOMParser.java:230)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:298)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.dozer.loader.xml.MappingStreamReader.read(MappingStreamReader.java:50)
	at org.dozer.loader.xml.MappingFileReader.read(MappingFileReader.java:58)
	at org.apache.camel.converter.dozer.DozerTypeConverterLoader.loadMappings(DozerTypeConverterLoader.java:313)
	at org.apache.camel.converter.dozer.DozerTypeConverterLoader.init(DozerTypeConverterLoader.java:226)
	at org.apache.camel.converter.dozer.DozerTypeConverterLoader.doStart(DozerTypeConverterLoader.java:390)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3059)
	at org.apache.camel.impl.DefaultCamelContext.doAddService(DefaultCamelContext.java:1209)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1170)
	at org.apache.camel.impl.DefaultCamelContext.addService(DefaultCamelContext.java:1166)
	at org.apache.camel.converter.dozer.DozerTypeConverterLoader.<init>(DozerTypeConverterLoader.java:126)
	at org.wildfly.camel.test.csv.CSVIntegrationTest.testMarshalViaDozer(CSVIntegrationTest.java:94)
```

CrossRef: https://issues.apache.org/jira/browse/CAMEL-9167

**Comment by tdiesler** [comment]
Out of date. Verified on current master and 2.3-redhat branch

**Comment by jamesnetherton** [comment]
Reopening as this is present with Camel 2.16
