### ISSUE TITLE
wireTap("log: ...") leads to script engine error

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#882]
For 

```
        // do something in camel that is transactional
        CamelContext camelctx = new DefaultCamelContext();
        camelctx.addRoutes(new RouteBuilder() {
            @Override
            public void configure() throws Exception {
                from("direct:start")
                .wireTap("log:org.wildfly.camel.test.jpa?level=WARN")
                .to("sql:update Account set balance = :#${body} where id = 3?dataSource=java:jboss/datasources/ExampleDS");
            }
        });
```
we get

```
Caused by: java.lang.IllegalArgumentException: No script engine could be created for: log
	at org.apache.camel.builder.script.ScriptBuilder.createScriptEngine(ScriptBuilder.java:334)
	at org.apache.camel.builder.script.ScriptBuilder.<init>(ScriptBuilder.java:111)
	at org.apache.camel.builder.script.ScriptBuilder.<init>(ScriptBuilder.java:90)
	at org.apache.camel.builder.script.ScriptLanguage.createExpression(ScriptLanguage.java:40)
	at org.apache.camel.model.ToDynamicDefinition.createExpression(ToDynamicDefinition.java:95)
	at org.apache.camel.model.ToDynamicDefinition.createProcessor(ToDynamicDefinition.java:70)
	at org.apache.camel.model.WireTapDefinition.createProcessor(WireTapDefinition.java:80)
	at org.apache.camel.model.ProcessorDefinition.makeProcessorImpl(ProcessorDefinition.java:534)
	at org.apache.camel.model.ProcessorDefinition.makeProcessor(ProcessorDefinition.java:495)
	at org.apache.camel.model.ProcessorDefinition.addRoutes(ProcessorDefinition.java:219)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:1069)
```

CrossRef: https://issues.apache.org/jira/browse/CAMEL-9159

**Comment by tdiesler** [comment]
Fixed in camel-2.16.0
