### ISSUE TITLE
Access to swagger api-docs gives 204

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#884]
Happens only on the 2.15.x branch

```
java.lang.AssertionError: expected:<200> but was:<204>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.wildfly.camel.test.swagger.SwaggerIntegrationTest.testRestDsl(SwaggerIntegrationTest.java:77)
```

CrossRef: https://issues.apache.org/jira/browse/CAMEL-9165

**Comment by tdiesler** [comment]
We upgrade to camel-2.16.x
