### ISSUE TITLE
LinkageError when loading CXF NamespaceHandler

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#902]
```
Caused by: java.lang.LinkageError: Failed to link org/apache/cxf/configuration/spring/AbstractBeanDefinitionParser (Module "org.apache.cxf:main" from local module loader @24b1d79b (finder: local module finder @68ceda24 (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.CR2/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.CR2/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.CR2/modules/system/layers/base)))
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
	at org.jboss.modules.Module.loadModuleClass(Module.java:560)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
	at org.jboss.modules.Module.loadModuleClass(Module.java:560)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
	at org.jboss.modules.Module.loadModuleClass(Module.java:560)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.apache.camel.component.cxf.spring.NamespaceHandler.init(NamespaceHandler.java:25)
	at org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.resolve(DefaultNamespaceHandlerResolver.java:131)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/factory/xml/AbstractSingleBeanDefinitionParser
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
	... 53 more
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.xml.AbstractSingleBeanDefinitionParser from [Module "org.apache.cxf:main" from local module loader @24b1d79b (finder: local module finder @68ceda24 (roots: /Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.CR2/modules,/Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.CR2/modules/system/layers/fuse,/Users/tdiesler/git/wildfly-camel/itests/standalone/basic/target/wildfly-10.0.0.CR2/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	... 57 more
```

**Comment by tdiesler** [comment]
Blocked by: https://issues.jboss.org/browse/WFLY-5532
