### ISSUE TITLE
Cannot create ElasticsearchEndpoint

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#904]
```
java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.Version
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166)
	at org.apache.camel.component.elasticsearch.ElasticsearchEndpoint.doStart(ElasticsearchEndpoint.java:97)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
```

**Comment by tdiesler** [comment]
done
