### ISSUE TITLE
Compatibility for spring based camel routes

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#984]

**Comment by tdiesler** [comment]
Currently fails on Karaf with 

```
Caused by: java.lang.IllegalArgumentException: BundleContext must be specified
	at org.apache.camel.util.ObjectHelper.notNull(ObjectHelper.java:316)
	at org.apache.camel.core.osgi.OsgiCamelContextHelper.osgiUpdate(OsgiCamelContextHelper.java:36)
	at org.apache.camel.osgi.OsgiSpringCamelContext.<init>(OsgiSpringCamelContext.java:37)
	at org.apache.camel.osgi.CamelContextFactoryBean.newCamelContext(CamelContextFactoryBean.java:59)
	at org.apache.camel.osgi.CamelContextFactoryBean.createContext(CamelContextFactoryBean.java:50)
	at org.apache.camel.spring.CamelContextFactoryBean.getContext(CamelContextFactoryBean.java:400)
	at org.apache.camel.spring.CamelContextFactoryBean.getContext(CamelContextFactoryBean.java:86)```
